### ISSUE TITLE
Minimum php version is too high on Debian Jessie and stretch

### ISSUE THREAD

**Issue by Akruidenberg** [marius-wieschollek/passwords#10]
The minimum version to install this app is PHP 7.1. The maximum version number of Debian without backports is 7.0. I''ve running a Openmediavault nas with debian Jessie. The default php version on Jessie is 5.6. Is it possible to get this app running with an older version of PHP?
Otherwise i cant' install this app and the only alternative is to run Passman.

**Comment by marius-wieschollek** [comment]
Hi, and thank you for your ticket.
I know that the PHP 7.1 requirement is considerably high, especially since most Linux distributions have long release cycles and even longer support cycles. However testing and maintaining the app for different PHP versions and different browsers is a lot of work and simply too much for me. The app is programmed for the PHP 7.1 language syntax and will therefore not work on PHP 7.0.
But wait, there is hope.

#### Can you migrate to PHP 7.1? ¹
@oerdnj does a great job providing up-to-date PHP builds for different systems. Even if you do not upgrade to PHP 7.1 i recommend his repository because it always provides the latest security patches.
If your system and configuration allows it, i would recommend to check if you can [use his repositories](https://deb.sury.org/#php-packages). I am using it on Ubuntu 14.04.

#### You could try something experimental ¹
I have never tried this before, but [spatie/7to5](https://github.com/spatie/7to5) says, it can convert PHP 7(.1) code to PHP 5.x code. You could try this for you, and if it works i'm sure that i can find a way to provide automatically converted builds of the software. (You need to convert the lib folder and then change the minimum php requirement in the info.xml)

#### If you were using the legacy app
If you were using the passwords app by Fallon Turner (or the legacy app which was maintained by me) you can still use it for a while. It is no longer supported, but if i'm notified of any security relevant issue before January 2019 i will still fix them. If you were not using this app, i do _absolutely not recommend_ to start using it now.

#### If nothing works for you
You can use Passman from @brantje.

¹ I always recommend to backup any data you don't want to loose before trying untested things. Just because nothing _should_ go wrong, it does not mean that nothing _will_ go wrong

**Comment by e-alfred** [comment]
It is also too high for Ubuntu 16.04 LTS which supplies 7.0 by default.

**Comment by marius-wieschollek** [comment]
Yes, i am aware of that. Debian currently ships PHP 7.0.27, Ubuntu 16.04 with PHP 7.0.22, Ubuntu 17.10 with PHP 7.1.8, the current PHP version is 7.2.1, the current PHP 7.1 version is 7.1.13. To make sure that the app works on all versions, i would (theoretically) have to cover 5 PHP versions x 3 Databases x 3 Browsers and soon x 2 Nextcloud versions. PHP 7.0 will be EOL at the end of [this year](http://php.net/supported-versions.php).

**I do not want to and will not support any version of any software for all eternity**
It is a well known problem that most Linux distributions already come with outdated software when they are released. This is especially the case for Debian. To solve this issue a lot of different solutions are available, from something as simple as a [PHP PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) to running [Nextcloud with Docker](https://hub.docker.com/_/nextcloud/).

Since i want to spend my development time for this project on new things and not on legacy software, i will only support the latest Nextcloud version and PHP versions with [active support](http://php.net/supported-versions.php) and simply require you to keep your system somewhat up-to-date.

### Upgrade your PHP to 7.2 on Ubuntu LTS
```
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get upgrade
```
