### ISSUE TITLE
Passwords app disables itself seemingly daily

### ISSUE THREAD

**Issue by discojon** [marius-wieschollek/passwords#106]
### System Information
- Nextcloud Version: 14.0.4
- PHP Version: 7.2
- Passwords Version: 2018.12.0
- Browser and Version: All
- Client OS and Version: All
- Server OS and Version: Dreamhost shared hosting, unsure of OS.

### Steps to reproduce
1. Tell us how to reproduce your issue. 
   -Attempt to retrieve password and find the app had disabled itself.  This occurs at least daily if not more frrequently.
2. Provide sample data if needed
3. Include relevant user settings and app settings if not standard

### Actual result
What does happen?
I have to manually enable passwords daily to utilize. 

### Expected result
What should happen?
Passwords should not automatically disable itself.

**Comment by marius-wieschollek** [comment]
Can you check the Nextcloud Log (Settings > Log) for any errors or exceptions caused by the passwords app?

**Comment by Pattex0o** [comment]
I´m getting the same error. 

> Error	no app in context	TypeError: Return value of OCA\Passwords\AppInfo\Application::registerCompatibilityClasses() must be an instance of OCA\Passwords\AppInfo\void, none returned
> 
>     /var/www/vhosts/domainname/httpdocs/apps/passwords/lib/AppInfo/Application.php - line 69:
> 
>     OCA\Passwords\AppInfo\Application->registerCompatibilityClasses()
> 
>     /var/www/vhosts/domainname/httpdocs/apps/passwords/lib/AppInfo/Application.php - line 57:
> 
>     OCA\Passwords\AppInfo\Application->registerDiClasses()
> 
>     /var/www/vhosts/domainname/httpdocs/apps/passwords/appinfo/app.php - line 8:
> 
>     OCA\Passwords\AppInfo\Application->__construct()
> 
>     /var/www/vhosts/domainname/httpdocs/lib/private/legacy/app.php - line 261:
> 
>     require_once("/var/www/vh ... p")
> 
>     /var/www/vhosts/domainname/httpdocs/lib/private/legacy/app.php - line 154:
> 
>     OC_App::requireAppFile("passwords")
> 
>     /var/www/vhosts/domainname/httpdocs/lib/private/legacy/app.php - line 127:
> 
>     OC_App::loadApp("passwords")
> 
>     /var/www/vhosts/domainname/httpdocs/cron.php - line 53:
> 
>     OC_App::loadApps()

**Comment by marius-wieschollek** [comment]
@Pattex0o You app disables itself because your server uses PHP 7.0 or older for cron jobs (PHP CLI). (The stack trace starts with `cron.php`, so its a cron job, and the `OCA\Passwords\AppInfo\void` means that the PHP version does not support the `void` return type introduced in PHP 7.1)

If the app works fine once you enable it in Nextcloud but keeps disabling itself every 15 minutes or so, it means that your Webserver (Apache/Nginx etc.) is configured to use PHP 7.1 or newer, but the command line interface is still configured to use PHP 7.0. 

You may have to install `php7.2-cli` or `php7.1-cli` manually and check the version of php with the command `php -v`:
```
user@host:~$ php -v
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
```
