### ISSUE TITLE
Crash after upgrade from Password-legacy

### ISSUE THREAD

**Issue by osos** [marius-wieschollek/passwords#11]
Just updated as the NextCloud notification said a new version of Password was available.

After the update internal server error occured.

Simply deleted the app to get the nextcloud working again.

Updated from previous version porperly the password-legacy.

**Comment by marius-wieschollek** [comment]
Hello @osos . Thanks for reporting the error.
Can you add some additional info?
Which version of Nextcloud are you using?
Which version of PHP are you using?
Which Database and version are you using?
Which version of the legacy app did you use?
Were errors logged in Nextcloud? (Check in Admin => Logging)
Did you run the `occ upgrade` command or the update via the webinterface?

**Comment by osos** [comment]
PHP 7.0 - Ubuntu 16.04

See 7.1+ is required.

However, running on production server with ubuntu 16.04 leaves no possibility to upgrade to php 7.1.

Effectively I must migrate the users to another password manager.

Please advise on possibilities.

**Comment by marius-wieschollek** [comment]
Well PHP 7.1 for ubuntu 16.04 would be available trough a [ppa](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/System-Requirements#php-requirements), but I'm not forcing you to do anything.

If you want to migrate to another password manager, you can downgrade to the [legacy app](https://github.com/marius-wieschollek/passwords-legacy/) and then use the CSV export. As long as you have not deleted any tables, the old data is still there.

Otherwise you can wait for version 2018.3, which will have a one time PHP 5.6+ compatible migration build.

**Comment by osos** [comment]
When do you expect the PHP 5.6+ compatible build?

**Comment by marius-wieschollek** [comment]
There is a PHP 5.6 compatible build on the migration page. (https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/_files/passwords.tar.gz). Since it is sadly not possible to automate the process for these builds, it is not very likely that i will keep it updated for a long time.
