### ISSUE TITLE
[Feature] Userinterface improvement suggestions

### ISSUE THREAD

**Issue by newhinton** [marius-wieschollek/passwords#110]
While i generally like the way you structured your app, and i think it looks really good as of now, there are two or three things that could be improved/added.

**1. Site-Preview**

Currently it is not clear to me how and when this preview is created. Maybe a little questionmark at the left button could clear that up.
Also, the ability to disable this preview could be useful to some (me :P)

**2. Edit Passwords**

Maybe move the "custom fields" section below the properties? makes the sites more balanced, and fits the logic, imho

**3. Favicons**

Currently the first letter of the url is used as an Icon for this credential. Maybe the favicon of the site could be fetched, or even a custom icon set by the user could replace it. 

**4. Revisions/SHA-1 Tooltips/Security**

It could be useful to add tooltips to those elements, so that a user who does not know what those mean can find it out easily.

**5. Custom Fields in Detailsview**

Maybe they deserve an own group to make them stand out?

**6. Clickable items which copy to clipboard with custom cursor-pointer**

This would allow the user to see what he can click and what not.

**7. Search**

In passman, i have added the ability to limit (or expand) the search to specific elements, so that the user can select if he wants to search for a label or only a username.

**8. Quickediting**

Add the ability to set editing as a single/doubleclick action

**9. Custom field with files**

Maybe a direct upload from the users filesystem would improve this

You see, there are only a few small things to improve on this otherwise VERY consistent and clean UI. 
If you want help with this list, say so :D

Oh, and before i forget it: happy birthday passwords! ;)

**Comment by newhinton** [comment]
Ah, i see :D 1&3 are a case of 'read the fucking manual' :D 

2&5 It makes sense to show custom fields as native fields when they are added by the user for his passwords, but wouldn't it also make sense to show that they are different if they only exist in a single password?

7 While functional, using such searchterms and syntax may be to complicated for users for daily use, wouldn't it be better to build an ui around it?

**Comment by msLinuxNinja** [comment]
If I may add another suggestion, the ability to mark a password as breached even if it doesn't show up in Hibp. Does that make sense?

**Comment by marius-wieschollek** [comment]
@msLinuxNinja Please open a new issue for your feature request.

**Comment by marius-wieschollek** [comment]
@newhinton 
- 1 => The option to disable previews will be in the next release.
- 8 => You choose an "Edit" options for click/dblclick in the advanced options. You can also set no option.

About 5: That could become very confusing if someone shares a password with you and some of your "standard" (but custom) fields are missing. Or if you share a password with someone and now your standard fields show up as custom fields in his account. 
I want to integrate custom fields as seamless as possible because i think that the difference between custom fields and default fields is not relevant to the average user. The fields shown for a password vary depending on which fields you fill in the edit form. The only always available fields are name and password. From the user perspective there will be some fields that always show up in the edit form and the other fields can be defined by him or clients like the browser extension if needed.

About 7: I think you mean something like the tag filter in Passman?

**Comment by newhinton** [comment]
Yeah, i see your point with confusion there, although i think it's not a perfect one, your current approach might be the better one.

Regarding the search: no, not like passman, they also dont have the ability to customise the search. I meant something like this:

![2019-01-26 22_37_55-passwords - mycloud](https://user-images.githubusercontent.com/25279821/51793075-1ebfd480-21bb-11e9-9ece-806df22c8c5a.png)

(this is from passman, but that feature is not on master)

This enables a user to quickly search for specific elements, without using your already existing filtertexts

Regarding 8: is that already available or in the upcoming version? Edit: Nevermind, upcoming

Also, if you want help (with anything), just say so ;)

**Comment by marius-wieschollek** [comment]
With the unified search feature there won't be any expansion of the search interface. I'm closing this.
