### ISSUE TITLE
CRITICAL! - Everyone Is seeing private saved Passwords  by default.

### ISSUE THREAD

**Issue by itsecbern** [marius-wieschollek/passwords#116]
### System Information
- Nextcloud Version: 15.04
- PHP Version: 7.2
- Passwords Version: 2019.2.0
- Browser and Version: Chrome - latest
- Server OS and Version: Hardened Linux CentOS 7.6

### Steps to reproduce
1. Install and enable "Passwords Plugin" / disable Lagacy API
2. Create one or two private passwords. E.g. facebook or gmail..
3. Login as other user or Impersonate an OTHER user.

### Actual result
You see now all private Passwords in cleartext from the other Account.

### Expected result
An emty list. -> Where the new Account can save his/her passwords.

**Comment by marius-wieschollek** [comment]
Just to make sure that we're talking about the same issue, please confirm that the behaviour described below fits your problem:

On a Nextcloud Instance that has the "Impersonate" app installed I ...
1. log in as an administrator.
2. go directly to the "Users" area without opening the Passwords App.
3. select the "Impersonate" option for a different account than my current one.
4. open the Passwords app impersonating the user.
5. now see that persons passwords.
6. log out of the impersonated account
7. open the Passwords App with my administrator account.
8. still see the Passwords of the user i impersonated.

After that, i will continue to see the impersonated user's passwords until i log out from my admin account and log back in.

**Comment by itsecbern** [comment]
Not exactly like this.. The problem appears after I created one or two password records on my Administrator account.  
When I now Impersonate an **unprivileged user** and open the Passwords App I see still my "adminstrator-saved" passwords on his account.

**Comment by marius-wieschollek** [comment]
It seems like the impersonate app is only changing the user of the current session. All other data in the session is left there. When you first open the passwords app, it stores the authentication data in the session. So the passwords app will just keep showing the passwords of the user that first opened the app.

I have added a patch to check if the authentication data belongs to the current user and invalidate if it not. Since passwords currently does not have a client side encryption and i think that most users do not expect admins to be able to access their passwords so easily i have also added a patch that cancels the session if the session user does not match the user that originally logged in.

There is already a nightly available with the patches, and i will release a regular update soon.

**Comment by itsecbern** [comment]
Ok cool.. Thank you! Good soulution :-)

**Comment by marius-wieschollek** [comment]
Fix is released.

**Comment by ksmolder** [comment]
I just updated to nextcloud 15.04 using Passwords  2019.2.1. Many of my users are configured using the LDAP backend. One of the implications is that the user name and login name do not match by design. The actual username is an auto-generated uuid while the login name is their email address.

As far as I can see, the applied patch breaks this setup as the verification whether username and login name are the same, always fails. The error displayed in the user interface when accessing the password app reads 

> The server was unable to complete your request.
> If this happens again, please send the technical details below to the server administrator.
> More details can be found in the server log.

Looking at the log file, the error message 

> User id and login name do not match. Passwords does not support impersonating.

is associated with the request id.

**Comment by ksmolder** [comment]
Just checked with temporary reverting to version 2019.2.0. This version makes the passwords accessible again...

**Comment by marius-wieschollek** [comment]
@ksmolder I actually had implemented a check for this. It seems like it did not correctly resolve login names to user ids leading to the error you experienced. I fixed it by reproducing the way Nextcloud handles this in their login.
I have released 2019.2.2 nightly and would be happy if you could check it before i release it tomorrow.

**Comment by ksmolder** [comment]
@marius-wieschollek I will do this this evening.

**Comment by ksmolder** [comment]
@marius-wieschollek I installed the nightly and I'm able to view the passwords again. Thanks for the quick fix.:+1: 

Just to mention: I did not validate whether the original bug this issue is about is still resolved.

**Comment by simonspa** [comment]
I can confirm that the bug described above doesn't appear anymore.

However, I find the remedy taken quite harsh. When impersonating a user and (even accidentally) clicking on the Passwords app, my whole session is void - not only the impersonation, but I also have to login anew to my own account. Is this intentional?

**Comment by marius-wieschollek** [comment]
@simonspa Yes, that is intentional. The user who originally logged in, the user who owns the data in the session and the actual session user could be three different users. It might be that an admin is currently impersonating someone, but it might also be some kind of attack. That's why the app simply cancels the session. That behavior will change after #80 is finished.
