### ISSUE TITLE
Unable to create file passwordsCache/113.json.gz

### ISSUE THREAD

**Issue by syssi** [marius-wieschollek/passwords#149]
### System Information
- Nextcloud Version: 16.0.1
- PHP Version: 7.3.5
- Passwords Version: 2019.5.0
- Browser and Version: Google Chrome 74.0.3729.157
- Client OS and Version: Debian Stretch
- Server OS and Version: Debian Stretch

### Steps to reproduce
1. I don't know.

### Actual result

I've updated nextcloud from 16.0.0 to 16.0.1. Afterwards this log message appeared very often.

### Expected result

No log message.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
The Log at the Nextcloud backend is empty.
```
</details>

### PHP Error Log
<details>
<summary>PHP Error log</summary>

```
May 22 10:24:18 leonard Nextcloud[16145]: {PHP} touch(): Unable to create file /srv/nextcloud/appdata_52XXXXXXXXXXX/passwords/passwordsCache/113.json.gz because No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#206
May 22 10:24:18 leonard Nextcloud[16145]: {PHP} stat(): stat failed for /srv/nextcloud/appdata_52XXXXXXXXXXX/passwords/passwordsCache/113.json.gz at /var/www/nextcloud/lib/private/Files/Storage/Local.php#142
May 22 10:24:18 leonard Nextcloud[16145]: {passwords} {"Exception":"OCP\\Files\\NotFoundException","Message":"\/appdata_52XXXXXXXXXXX\/passwords\/passwordsCache","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Node\/Node.php","line":274,"function":"get","class":"OC\\Files\\Node\\Root","type":"->","args":["\/appdata_52XXXXXXXXXXX\/passwords\/passwordsCache"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/SimpleFS\/SimpleFile.php","line":126,"function":"getParent","class":"OC\\Files\\Node\\Node","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/SimpleFS\/SimpleFile.php","line":108,"function":"checkFile","class":"OC\\Files\\SimpleFS\\SimpleFile","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Services\/FileCacheService.php","line":231,"function":"putContent","class":"OC\\Files\\SimpleFS\\SimpleFile","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Helper\/SecurityCheck\/AbstractSecurityCheckHelper.php","line":170,"function":"putFile","class":"OCA\\Passwords\\Services\\FileCacheService","type":"->","args":["113.json.gz",null]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Helper\/SecurityCheck\/HaveIBeenPwnedHelper.php","line":85,"function":"writePasswordsFile","class":"OCA\\Passwords\\Helper\\SecurityCheck\\AbstractSecurityCheckHelper","type":"->","args":[...
```
</details>

**Comment by syssi** [comment]
The folder `appdata_52XXXXXXXXXXX/passwords/passwordsCache` exists, is writable but empty.

**Comment by Nikhos** [comment]
I've got the same problem

**Comment by marius-wieschollek** [comment]
@syssi Thanks for your bug report. The PHP stack trace helped me a lot.

It seems that there are two problems here: The background job to check for compromised passwords clears its cache way too often because it always believes that the cache is invalidated.
Nextcloud also caches all appdata folders once they are opened for the first time but does not update that cache when a folder is deleted. So when the background job clears the cache by deleting the folder and then requests that folder again to write into it, Nextcloud returns a cached folder that does not actually exist anymore.

I have added a workaround that makes sure that the Nextcloud cache is cleared after the folder is deleted and also fixed the cache validation status issue in the 2019.6.0 nightly.

You can install the nightly by checking the `Show Nightly Updates in "Apps"` option in the admin settings and then looking into the Apps section or by installing it manually from the [app store](https://apps.nextcloud.com/apps/passwords/releases).

**Comment by syssi** [comment]
> You can install the nightly by checking the Show Nightly Updates in "Apps" option in the admin settings and then looking into the Apps section or by installing it manually from the app store.

Could you guide me to this setting? I've checked /index.php/settings/admin multiple times without success.

**Comment by marius-wieschollek** [comment]
This setting is in the section of the passwords app. The url is like this:
https://yourhost/index.php/settings/admin/passwords#passwords-nightly-updates

The regular update will come out this weekend.

**Comment by syssi** [comment]
Thanks a lot! I've updated the password app. I will check if the error is gone now.

**Comment by syssi** [comment]
Thanks for your support! This issue is fixed. The errors messages are gone!
