### ISSUE TITLE
double OTP request with 2019.7.1-build2984

### ISSUE THREAD

**Issue by nextgen-networks** [marius-wieschollek/passwords#158]
### System Information
- Nextcloud Version: 16.0.1
- PHP Version: 7.3.6
- Passwords Version: 2019.7.1-build2984
- Browser and Version: Chrome 74 (latest)
- Client OS and Version: Win 10 Pro 1903
- Server OS and Version: Ubuntu 16.04.6
- OTP-App: Two-Factor TOTP Provider 2.1.2

### Steps to reproduce
1. You need to have OTP enabled.
2. when accessing Passwords a OTP-Code is required
3. after providing the OTP-Code one time you will be promted to provide a OTP-Code (again!)
4. you can use the old OTP-Code or wait for a new one that does not matter - after typing in a valid OTP-Code a second time you will get access to Passwords

### Actual result
You need to type a OPT-Code two times.

### Expected result
You need to have to type a OPT-Code only one time.

**Comment by marius-wieschollek** [comment]
The nightly 2019.7.0-build3015 should fix this issue.

Since you have one of the builds with the 2019.7.1 versioning error you need to update it manually by downloading it from the [app store](https://apps.nextcloud.com/apps/passwords/releases) and placing the files in your apps directory.

This feature also only exists in nightlies and will be disabled in the final version.
