### ISSUE TITLE
HTTPS Issue Reverse Proxy

### ISSUE THREAD

**Issue by mitchy112** [marius-wieschollek/passwords#16]
Im getting the error:
HTTPS Required

I think this is because im on a reverse proxy, and the traffic from my reverse proxy to nextcloud is http it doesnt recognize this. Is there a way to fix this? I dont want to get rid of my reverse proxy since it handles all my certificates and renews them automatically.
I would love a solution.

If you need more info just drop me reply

**Comment by marius-wieschollek** [comment]
You are correct. Currently the app only recognizes HTTPS behind a proxy of `overwriteprotocol` is set to `https`. Ticket #15 addresses this issue. In the upcoming version, any connection that is recognized as secure by Nextcloud will be allowed. There is no way to disable the check, but you can set `'forcessl' => true` in the config.php to pass the check. Since Nextcloud itself does not use the option (anymore) there should be no side effects.
