### ISSUE TITLE
[irritation] I'm loading the list and some sites throw to a subdomain...

### ISSUE THREAD

**Issue by WNYmathGuy** [marius-wieschollek/passwords#160]
**Current Status**
If I have a password entered as a `Website: https://a-domain.tld` and `Website: https://subdomain.a-domain.tld` one of them is listed as `Weak (Duplicate)` in the Nextcloud web interface.

**Feature Description**
Because some sites accept the username on `https://a-domain.tld` but throw to `https://subdomain.a-domain.tld` to receive the password, it's conveinent for me to have both available in the browser extension. Subdomains arent recognised by the browser extension as part of a larger domain, so I just entered both into Nextcloud with the web interface. They are neither Weak nor Duplicates.

**Additional context**
In the short term maybe you can change the duplicate identifier for the Nextcloud applicaton to recognize subdomains as different? 

In the long term maybe the browser extensions should recognise a subdomain page is part of the main domain's universe and show all the available logins for the FQDN?

**Comment by marius-wieschollek** [comment]
For the extension it is planned that you can use multiple urls in the future (see [#45](https://github.com/marius-wieschollek/passwords-webextension/issues/45)).

In the app, the duplicate check is done with the password hash. Since we are already testing client side encryption i see no use in the implementation of a server side feature that requires the ability to decrypt the password data.
