### ISSUE TITLE
Version 2019.7.1 breaks theme

### ISSUE THREAD

**Issue by XUBIUM** [marius-wieschollek/passwords#168]
Remember not to include personal data as this is public.
-->

### System Information
- Nextcloud Version: 16.0.3 (happens in previous versions as well)
- PHP Version: 7.2
- Passwords Version: 2019.7.1
- Browser and Version: Firefox 67.0.4 (64-bit)
- Client OS and Version: Windows 10 1809
- Server OS and Version: Ubuntu 18.04.2

### Steps to reproduce
1. Configure a theme for Nextcloud (disable theming app and have the theme in nextcloud/themes, also configure it on config.php)
2. Upgrade to version 2019.7.1
3. Enter to the passwords app

### Actual result
Theme is broken, loads the logon screen background first and then the top bar remains wih the highlight (secondary) color that is configured at defaults.php in the theme

### Expected result
Don't break the theme (as with previous versions)

### Nextcloud log
No log entry produced

![PasswordsIssue](https://user-images.githubusercontent.com/36968377/60942959-26c38a80-a2aa-11e9-9d6e-c40e2b0ff9ef.gif)

</details>

**Comment by buzter** [comment]
Same behaviour here:
Nextcloud Version: 16.0.2
PHP Version: 7.2
Passwords Version: 2019.7.1
Browser and Version: Opera 62.0.3331.43
Client OS and Version: Windows 10
Server OS and Version: Synology DSM 6.2

**Comment by XUBIUM** [comment]
Hi buzter, 
Are you sure that you had Passwords Version 2019.7.1 in Nextcloud 16.0.2? Because I have tested 2019.7.1 even in 15.x.x and I get the same broken theme behavior.

**Comment by marius-wieschollek** [comment]
Passwords 2019.7.0 adds support for 2FA and master passwords. This is why there is a login screen inside the app. If you do not use any of the options, the login screen will disappear on itself but the process is the same. After this, the header background color is restored to its default color - which is the value of `--color-primary`. If you have a custom css stylesheet, you can either use
```
:root {
   --color-primary: #123456;
}
```
to set the color globally, or
```
#header {
   --color-primary: #123456;
}
```
to set it just for elements in the header, or

```
body#body-user.pw-authorized #header {
    background-color: #123456 !important;
}
```
to specifically set the final color for the header after the login screen.

I would not see this as a bug since the behavior of the login screen works fine with the default theming of Nextcloud as well as the theming app.

**Comment by XUBIUM** [comment]
Hello,

color-primary as set in the defaults.php file of a theme is used by Nextcloud for highlighting. For example when hovering over app icons or the left column options. The background color for the login screen is set in the server.css file in the atrribute background-color under #body-login and the background color for the menu bar is set also in the server.css file in the background-color attibute under #header

I believe the issue is the use of color-primary (the highlighting color) for backgrounds. As far as I remember the default Nextcloud theme uses the same blue color for highlighting, and that would be the reason why it works well with the default theme.

**Comment by buzter** [comment]
> Hi buzter,
> Are you sure that you had Passwords Version 2019.7.1 in Nextcloud 16.0.2? Because I have tested 2019.7.1 even in 15.x.x and I get the same broken theme behavior.

You seem to be right. In NC 16.0.1 Passwords 2019.6.0 was installed. Sorry...

**Comment by buzter** [comment]
> I would not see this as a bug since the behavior of the login screen works fine with the default theming of Nextcloud as well as the theming app.

@marius-wieschollek Thx, Your hint works fine for me. In addition I now understand the behaviour of NC when clicking the password icon...

**Comment by XUBIUM** [comment]
> 
> 
> Hello,
> 
> color-primary as set in the defaults.php file of a theme is used by Nextcloud for highlighting. For example when hovering over app icons or the left column options. The background color for the login screen is set in the server.css file in the atrribute background-color under #body-login and the background color for the menu bar is set also in the server.css file in the background-color attibute under #header
> 
> I believe the issue is the use of color-primary (the highlighting color) for backgrounds. As far as I remember the default Nextcloud theme uses the same blue color for highlighting, and that would be the reason why it works well with the default theme.

Hello @marius-wieschollek 

Were you able to check this message? Please do let me know if I can provide more information. 

Best regards,

**Comment by marius-wieschollek** [comment]
@XUBIUM I'm currently checking it

**Comment by marius-wieschollek** [comment]
@XUBIUM 
Nextcloud itself sets the color of the header with the CSS variable:
```server.css
#body-user #header, #body-settings #header, #body-public #header {
    [...]
    background-color: var(--color-primary);
    [...]
}
```

You can overwrite that in the server.css file of your theme, but that will not overwrite the actual css variable. The Scss variables from the default.php are seemingly not converted into css variables. That is why the color is different after the login screen. There are `color-primary-text` (which is used for text) and `color-primary-element` (which is used for interactive elements) variables available, so i would argue that the use of `color-primary` is right since that seems to be it's supposed usage.

**Comment by XUBIUM** [comment]
OK Marius, thanks for checking into this. 
Best regards
