### ISSUE TITLE
Hide "https://" from the URL-field

### ISSUE THREAD

**Issue by szaimen** [marius-wieschollek/passwords#177]
**Current Status**
Each time I create a new password, I am forced to enter "https://" before the main URL.

**Feature Description**
I should not be forced to do that. Instead it should be entered automatically and/or not shown for my eyes because that improves the clarity of the URL. 

**Additional context**
Maybe add a dropdown menu for "http://" or "https://" and make "https://" to the default.
"Custom" could be also be an entry which would represent the current version. (enter it manually)

**Comment by szaimen** [comment]
Here is another way how that could be solved:
https://forums.bitfire.at/topic/2117/please-make-entering-http-s-for-the-basis-url-optional

**Comment by godfuture** [comment]
Please keep in mind that domains are not only used in browser as url, there are many other use cases where it makes sense to leave out the https://. The domain field may be an AD domain, a host or even other protocol-URI like mailto://.

**Comment by szaimen** [comment]
I know, but then the protoc would be manually written by the user, I guess.

The link that I referenced does it this way: if nothing is entered, they automatically prepound https:// to the url.

**Comment by marius-wieschollek** [comment]
So 2021.4.0 updates the edit form. If you enter an invalid url (anything not matching `<[words,+,-]>:<any text>`), the value will just be prefixed with https://. 

I went with this approach because i found that dropdowns put unnecessary limits to the available protocols. It would also make entering an url more complicated for users and require special handling of common use cases like copy&pasting urls.

I don't think we should hide parts of urls anywhere in the ui. If you have a long login url, omitting the https won't make much difference. Users should also be able to see where the url leads them right away without any restriction.

**Comment by szaimen** [comment]
> So 2021.4.0 updates the edit form. If you enter an invalid url (anything not matching `<[words,+,-]>:<any text>`), the value will just be prefixed with https://.

Sounds good to me 👍

So I guess this issue can be closed then?
