### ISSUE TITLE
Creating password failed, 

### ISSUE THREAD

**Issue by AGIT7887** [marius-wieschollek/passwords#179]
### System Information
- Nextcloud Version: 16.01
- PHP Version: 7.3.6
- Passwords Version: 7.2
- Browser and Version: any
- Client OS and Version: 
- Server OS and Version:

### Steps to reproduce
1. 
2. 
3. 

### Actual result
Please help. Why the application stops functioning correctly when the server does not have access to the Internet. After blocking access to the internet, you can not create any new new password. The message "Creating password failed" appears.

### Expected result
The application should function correctly without the need to access the public network

### Nextcloud log
<details>
<summary>Nextcloud log

Error | passwords | Exception: HIBP API returned invalid response. Status: 0/var/www/nextcloud/apps/passwords/lib/Helper/SecurityCheck/HaveIBeenPwnedHelper.php - line 34: OCA\Passwords\Helper\SecurityCheck\HaveIBeenPwnedHelper->isHashInHibpDb("c50267b906a ... 0")/var/www/nextcloud/apps/passwords/lib/Helper/SecurityCheck/AbstractSecurityCheckHelper.php - line 91: OCA\Passwords\Helper\SecurityCheck\HaveIBeenPwnedHelper->isHashSecure("c50267b906a ... 0")/var/www/nextcloud/apps/passwords/lib/Hooks/PasswordHook.php - line 221: OCA\Passwords\Helper\SecurityCheck\AbstractSecurityCheckHelper->getRevisionSecurityLevel(OCA\Password ... 7})/var/www/nextcloud/apps/passwords/lib/Hooks/PasswordHook.php - line 91: OCA\Passwords\Hooks\PasswordHook->checkSecurityStatus(OCA\Password ... 7})/var/www/nextcloud/apps/passwords/lib/Hooks/Manager/HookManager.php - line 86: OCA\Passwords\Hooks\PasswordHook->preSetRevision(OCA\Password ... l}, OCA\Password ... 7})<<closure>>OCA\Passwords\Hooks\Manager\HookManager->__call("passwordPreSetRevision", [ OCA\Passwo ... }])/var/www/nextcloud/lib/private/Hooks/EmitterTrait.php - line 99: call_user_func_array([ OCA\Passwo ... "], [ OCA\Passwo ... }])/var/www/nextcloud/apps/passwords/lib/Hooks/Manager/HookManager.php - line 46: OC\Hooks\BasicEmitter->emit("OCA\\Passwords\\Db\\Password", "preSetRevision", [ OCA\Passwo ... }])/var/www/nextcloud/apps/passwords/lib/Services/Object/AbstractModelService.php - line 121: OCA\Passwords\Hooks\Manager\HookManager->emit("OCA\\Passwords\\Db\\Password", "preSetRevision", [ OCA\Passwo ... }])/var/www/nextcloud/apps/passwords/lib/Controller/Api/PasswordApiController.php - line 147: OCA\Passwords\Services\Object\AbstractModelService->setRevision(OCA\Password ... l}, OCA\Password ... 7})/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Passwords\Controller\Api\PasswordApiController->create("www", "www", "", "none", "c50267b906a ... 0", "www", "", "", "[]", "00000000-00 ... 0", 1564175492, false, false, [])/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Password ... {}, "create")/var/www/nextcloud/lib/private/AppFramework/App.php - line 126: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Password ... {}, "create")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("PasswordApiController", "create", OC\AppFramew ... {}, { _route: "p ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "p ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "p ... "})/var/www/nextcloud/lib/base.php - line 975: OC\Route\Router->match("/apps/passw ... e")/var/www/nextcloud/index.php - line 42: OC::handleRequest()
-- | -- | --

</summary>

```
See Settings > Log  (Copy Raw)
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Press F12, copy what you see
```
</details>

**Comment by marius-wieschollek** [comment]
_Hi @AGIT7887 . If you open an issue on GitHub, please always fill out the forms completely to make sure all necessary information is provided._

_This ticket would also have been better in our [forum](https://help.nextcloud.com/c/apps/passwords) since our [system requirements](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/System-Requirements#third-party-services) specify that the app expects access to some third party services and a connection error when those can not be reached is therefore not a bug._

**To solve your issue:** When you save a new password, the app creates an SHA-1 hash and then tries to download a list of similar hashes from [haveibeenpwned.com](https://haveibeenpwned.com/) to check if the password appears in hacked password lists from the internet. If that check fails, the entire action fails. 
In the admin settings of Nextcloud you can **choose a different service**. The **10 Million passwords** service downloads a list of passwords and stores it locally. After that it does not need a connection. (Unless the cache is cleared) If you have a server with low RAM (< 4GB) you can use the **1 Million passwords** list. The download is done with a background job that runs once per day. You can see that the update is finished if the passwords cache has 4096 files in it.
**Note:** If the list gets updated or we switch to a different list, the app will forcefully clear the cache and try to download the new list. 


We do not support servers with no internet access, but if you change these settings it should work. You also need to [self host the user manual](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/User-Handbook#self-hosting-the-handbook) since the app will try to open the handbook sometimes.

| Setting | Offline Option |
|---|---|
| Password Generator Service | Local dictionary (if installed) or Random characters |
| Favicon Service | None |
| Website Preview Service | None |
| Server survey participation | None |
| Show Nightly Updates in "Apps" | No |
