### ISSUE TITLE
"Hide users from guests" option applied to all users

### ISSUE THREAD

**Issue by Alphacoder1337** [marius-wieschollek/passwords#180]
If i try to share a password with a user, it does not show me the user in the autocomplete field (see screenshot 1). Only admin users are listed there, but sharing is not limited to a specific group.

About 1 week ago, this worked without any problem (see screenshot 2).
Also, sharing in other apps and files is working fine.

![1](https://user-images.githubusercontent.com/15197794/62129159-57f61000-b2d6-11e9-93c7-3324b1839dbf.png)
![2](https://user-images.githubusercontent.com/15197794/62129162-588ea680-b2d6-11e9-956f-97c6763861e0.png)

**Comment by marius-wieschollek** [comment]
_Hi @Alphacoder1337  if you open an issue on GitHub, please use one of the options available and fill out the form. This ensures that all necessary information is there._

Can you please check which version of the app you're using? Can you also check if the [guests](https://apps.nextcloud.com/apps/guests) app is installed on the system?

**Comment by Alphacoder1337** [comment]
Hello,
sry this is my first post on github. Please tell me which option should i use and where can i choose it?

Im using Nextcloud 16.0.3, the latest passwords app version 2019.8.0 and yes im also using the guests app. I can neither share with guests nor with "normal" users, only with users in the "admin" group.

**Comment by marius-wieschollek** [comment]
Since sharing used to work but does no longer work as expected this is most likely a bug. The option "Bug Report" would have been the best choice here.

Since you noticed that sharing works within your group but not with any other user, i think the integration of the guests app is the reason. It was added in 2019.8.0. If the option "Hide other users from guests" is set, the passwords app will restrict _any_ user to their group, not just guests.

I will notify you when a patch is available.

**Comment by Alphacoder1337** [comment]
Thank you, very cool!

Sry, but it seems that i cant set labels on github. Maybe i need to have some posts / reputation for this like on stackoverflow...

Yes, this option is set in my installation. Your reasoning sounds comprehensibly.

**Comment by Alphacoder1337** [comment]
Just installed the latest update, its working now!
Thanks you very much!
