### ISSUE TITLE
Integration of favicon-service

### ISSUE THREAD

**Issue by Ra72xx** [marius-wieschollek/passwords#191]
Right now the app issues a warning that  the user is encouraged to run his/her own favicon service. While I understand the rationale behind this move, and there is a good how-to available, I consider this a drawback for the up-to-now very good user experience.

The user is forced to run a new server software which is not even readily available in pre-packaged form for the typical distributions.
For users using low-end hardware (read: RPi) this is an additional burden.
"besticon" is only available in x84 binaries or docker images. Both not an real option for RPis etc.

For me I draw the conclusiion that this is simply too much of effort for a (more cosmetic) pimp-up of the password app ui.

So I propose (without being able to help here) that the favicon stuff should be transparently included in some form in the core passwords nextcloud app.

**Comment by Ra72xx** [comment]
I add to myself that you obviously can select other icon services in the admin settings. However, the recommended solution ist BestIcon, which has the above mentioned drawbacks. At least I would remove the "recommended" tag from this setting.

**Comment by marius-wieschollek** [comment]
_Please always use the templates when creating an issue report_

Thanks for your feedback. I have updated the guide to include [an option for ARM devices](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Besticon-Self-Hosting#build-it-yourself-suggested-for-raspberry-pi-arm) and also linked a self compiled arm binary from my raspberry.

I have also added a section to install it as a systemd service which runs automatically on system boot.

> The user is forced to run a new server software [...]

The user is not forced to do anything. I ask you to host it yourself because the public instance has been using up it's quota for the last three months because 1000+ servers are using it. You're free to continue using it, it might just not work sometimes.

> [...] which is not even readily available in pre-packaged form for the typical distributions.

The maintainers of the official PPAs put in an unbelievable amount of effort to support all the packages in the archives. Of course you can't expect them to add any project from GitHub.

>  "besticon" is only available in x84 binaries or docker images. Both not an real option for RPis etc.

You can compile besticon from source on your RPI.

> For me I draw the conclusiion that this is simply too much of effort for a (more cosmetic) pimp-up of the password app ui.

I can't agree with that. Hosting it on Heroku for free requires making a free account and then clicking a link. Even compiling it from source on my RPI was surprisingly easy.

> So I propose (without being able to help here) that the favicon stuff should be transparently included in some form in the core passwords nextcloud app.

The app already offers a local favicon service. It's just not as good as besticon. It also means that the app needs to download the source of the website to the server, parse it and then download one or more icons to find the best one. This could be unwanted for some users.

From all the services there are, besticon is the best one. It's the most likely to get a good result. You can host it yourself. You can read an modify the source code. It is easy to integrate into the app. This is why it is and stays the recommended option.

It might be that i have access to a more powerful option for the public instance in the future. If that happens i will remove the notification again. Until then i just hope that at least some users switch to their own instance.

**Comment by Ra72xx** [comment]
Thanks fo the quick response.
