### ISSUE TITLE
[QUESTION] Watchout4snakes

### ISSUE THREAD

**Issue by Pofilo** [marius-wieschollek/passwords#201]
In the admin settings, when chosing for the **Password Generator Service**, **watchout4snakes.com** is said as recommended. Why is it more recommended that a local dictionary or random characters ?
Why is random characters not the recommended one ?

**Comment by marius-wieschollek** [comment]
The **local dictionary** is often not installed (It's default if available, but only < 20% use it). I have no control over it's contents and it could consist of the same three words over and over again.

The **random characters** generates cryptographic secure random strings but ... [also hard to remember](https://xkcd.com/936/) and [no longer the recommended way of making passwords](https://pages.nist.gov/800-63-3/sp800-63b.html#appA). All that randomness is not going to help if you use the same random password everywhere. Instead the app will encourage you to use longer passwords which you can remember and monitor that password's security.
**watchout4snakes.com** provides a source of random words that will work on most servers without issue. You can specify the word type in the api request and therefore create passwords that are long and still easy to use for the average person.

All passwords are checked against the configured security check provider (where i would recommend HiBp because noone else has that many hacked passwords) so you can be sure that is isn't common.

I'm also always open for other suggestions.

**Comment by Pofilo** [comment]
Okay, I got that for the **local dictionary**. However, I don't see why it is relevant to have passwords more easy to remember. If we use a password manager, it is to only remember the master password, the others can be totally randoms right ?

However, it is also better to have 20 characters "generated with watchout4snakes.com" than a 8 characters password with random characters so I'll not argue more :)

Good job tho ! Keep it up !
