### ISSUE TITLE
Nextcloud behind proxy - no internet direct access

### ISSUE THREAD

**Issue by alexdip** [marius-wieschollek/passwords#202]
Hi, password app crash when nextcloud server (redhat family)  is behind proxy for internet connection. The problem is created when the server is not directly connected to the internet but uses the proxy it serves. 
I checked on my firewall and I see direct connections without going through the proxy to the following IPs:
- 151.101.240.133
- 50.63.197.145
- 207.241.224.2
when I block direct access to the internet the app crashes.
in my opinion it is a big security problem.

**Comment by marius-wieschollek** [comment]
_If you create a ticket please fill out the form and provide all the requested information._

> password app crash

is a very vague description of what happens.

The IPs seem to be fine as they are Github (151.101.240.133), watchout4snakes.com (50.63.197.145) and archive.org (207.241.224.2). All of those are listed in the [system requirements](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/System-Requirements#third-party-services).

The app does not support a proxy for outgoing requests because this feature was not requested until now. I have added some modifications to the nightly version which should make the app respect the Nextcloud proxy and proxyuserpwd settings for most requests. Feel free to download the [nightly](https://apps.nextcloud.com/apps/passwords/releases?platform=17#17) from the appstore and give it a try.

**Comment by alexdip** [comment]
perfect. I await implementation in production. not all using nextcloud directly connected to the internet. thank you so much
