### ISSUE TITLE
Support Bitwarden import

### ISSUE THREAD

**Issue by jcklpe** [marius-wieschollek/passwords#210]
there doesn't appear to be any ability to import from Bitwarden. I found a ticket from October that indicated that it could be imported using bitwarden csv but I do not see that anywhere in the menu?

**Comment by marius-wieschollek** [comment]
I will add support for the JSON file which you can export from the Bitwarden website in the next release. (2020.1.0) I will also add an import profile for the CSV import. You can already test it in the nightlies which you can download from the [app store](https://apps.nextcloud.com/apps/passwords).

You can already import the CSV file from Bitwarden if you choose the option "Other / Custom CSV" from the format list. You can leave the options in step 2 as they are. In step 3 you need to map the fields as follows: 1: Tags, 2: Favorite, 3: Folder, 4: Label, 5: Notes, 6 Custom Fields, 7: Url, 8: Username, 9: Password.
![grafik](https://user-images.githubusercontent.com/8255857/70392629-4807de80-19e2-11ea-8ee5-ff87a83c041e.png)
You can also switch fields 1 and 3, but the way Bitwarden uses folders they're more like tags in Passwords.

I would recommend using the JSON import since the Bitwarden CSV does not contain all data.
It is not possible to import files from Bitwarden since a) we do not support files and b) i couldn't test it since it's a premium feature. There will be no warning (like we have for Enpass) if files are ignored during import.
