### ISSUE TITLE
password share

### ISSUE THREAD

**Issue by xaha24** [marius-wieschollek/passwords#22]
Hi, great work. very nice app.
If you have users mapped from LDAP usernames are not suitable for user search to share a password.
It would be better searching users by their external names. A hit list with incomplete name input would be great.

**Comment by magoralczyk** [comment]
I am having the same problem: I can share a password to another user (both ldap): I can find the other user in the search dialogue and the password is shown in the shared passwords list, but when I login with the other account and look into the "shared with me" List, I get the empty page with the spinner.
I do not know, if it has anything to do with ldap, but in my case, the nextcloud IDs/usernames are == ldap usernames (not standard in the ldap plugin).

**Comment by marius-wieschollek** [comment]
@andreashartke I didn't have time to finish the sharing ui for the current version. The next version will have a dropdown to help selecting users by name. The [current nightly](https://apps.nextcloud.com/apps/passwords/releases?platform=13#13) already implements the feature.

@magoralczyk I think i found the issue you mentioned. When you share a password, it can take up to 15 minutes until the other person sees it. Sharing is completed by a background job. While a share is not completed, the "Shared with me" section currently does not work properly for the receiver. This also has been fixed in the [current nightly](https://apps.nextcloud.com/apps/passwords/releases?platform=13#13) and the section should always work.

**Comment by magoralczyk** [comment]
Yes, you are right, the problem solved itself. Thanks for fixing so fast, you are quite a busy beaver ;)

**Comment by xaha24** [comment]
I've tested the nightly implementation. The sharing UI works fine with LDAP users too. 
Many thanks.

**Comment by magoralczyk** [comment]
I did also install the nightly version and now I am having new problems, I did not have before:
When I click on details, I get " the modulel Marked could not get loaded. Possibly the connection to Nextcloud is broken" and when I click on edit, I get " the modulel SimpleMde  could not get loaded. Possibly the connection to Nextcloud is broken" and the NoticeBox is no longer present.

**Comment by marius-wieschollek** [comment]
@magoralczyk ok, thank you. That is indeed some new stuff that seems to be broken there. 
Can you 1. Check the Network tab in the developer tools when opening the details or the edit window and 2. Open a new issue with your findings?
