### ISSUE TITLE
Very slow passwords list feature

### ISSUE THREAD

**Issue by bertrand-benoit** [marius-wieschollek/passwords#221]
Hi,

I use the passwords application since about 6 months, but now that I have all my passwords registered (all means ONLY about 450 passwords), the List feature is very slow => page loads usually between 6 and 20 seconds.
Even with:
 - recommended Nextcloud configuration : 'memcache.local' => '\OC\Memcache\APCu',
 - PHP opcache enabled, 
 - Varnish cache of my Gandi provider
 - 'none' configuration on Password favicon (to reduce extra loading, even if it is better with recent update with Ajax async loading)

### System Information
- Nextcloud Version: 17.0.2
- PHP Version: 7.3.6
- Passwords Version: 2019.12.1
- Browser and Version: Firefox 71.0 (64-bit)
- Client OS and Version: Fedora 31 - Kernel 5.3.16-300.fc31.x86_64
- Server OS and Version: Gandi Linux 4.9.124-paas-2270098

### Steps to reproduce
1. Simply load /index.php/apps/passwords/#/all

### Actual result
Page loads usually between 6 and 20 seconds

### Expected result
Page loads in less than 2 seconds.

FYI: it is lightly better with indexex proposed in the following issue #139, but it is still:
 -   [6122 ms XHR loading](https://ibb.co/g9HG1mv)
 - [12683 ms images loading](https://ibb.co/QHmw0bN)

**Comment by marius-wieschollek** [comment]
Your results are within the expected time for listing all passwords.

- APCu is not used by the passwords app.
- OPcache is a bytecode cache for PHP code, it only speeds up the compilation.
- Varnish is a full page cache and will probably not cache anything since Nextcloud sets the cache headers to `no-cache, no-store, must-revalidate` because it only delivers user specific content which should not be cached.

To fetch all passwords, each of them needs to be decrypted. That is where most of the time is spent.
There is not much that can be done against this. I recommend using folders or tags as these views are a lot faster.

The images should be cached in the browser for 7 days after they are loaded once. If that is not the case, your server configuration is wrong.

**Comment by bertrand-benoit** [comment]
Hello @marius-wieschollek,

Thanks for your answer.
Ok for all the cache systems, and for the images.

Anyway, I already tried to set tags or folders as default view, and true it was quite faster; BUT about 90% times I go on the Passwords App under my Nextcloud, it is to perform a Search; and this feature seems to still need to fetch 100% of password before answering, like if search was performed on client side?
And if I remember well, when searching from a Folder, only passwords of corresponding folder are reachable by the search (which is the opposite of my need because usually I do NOT know in which folder it may be).
Is there any way to optimize the performance for the search feature?

**Comment by marius-wieschollek** [comment]
> like if search was performed on client side?

That's exactly what happens. Search on the server does not work with client side encryption and we still have to decrypt every password before we can search in it. In the end it's just faster to load all passwords and search in those client side since if they're all there you don't need to fetch them from the server again.

>  Is there any way to optimize the performance for the search feature?

Yes and i'm working on this. I'm currently developing a new search for the new browser extension and i hope to integrate this into the main app afterwards. With that, data will only be loaded once and then every view will load instantly.
And i hope that i will be able to load the data initially from the extension when the app is opened which would remove any loading time.

**Comment by bertrand-benoit** [comment]
Ok, very nice if you reach this goal, but what about passwords' security on client side?
I already use Passwords' extension on daily manner, and I'm very happy with it.
