### ISSUE TITLE
Documentation for csv import

### ISSUE THREAD

**Issue by magoralczyk** [marius-wieschollek/passwords#24]
It seems, there are a few possibilities to import passwords from csv (passwords, passman, other). I have a csv file from keepass, which has the following columns:
"Account","Login Name","Password","Web Site","Comments"

Of cource I could  work my notepad++ magic and change stuff around, but I do not know what the importer expects. What I did is, to export a password from passwords to csv, and then fill the fields like the export does, regarding, that I do not have an ID and Version ID String, nor a changedate. Since that did not work, I need better instructions how to modify my csv, so that it gets imported.

**Comment by marius-wieschollek** [comment]
The importer should have an option to import a custom csv (but this only works if #26 is fixed) where you can map the fields yourself. But i added a "Keepass CSV" option in build 1997 which does all the important stuff.

**Comment by magoralczyk** [comment]
Thanks for all your services! This is really outstanding, how fast you implement features. Now a comment for the keepass import:
I tried a file with 102 lines and it did not work (sth like "json argument 9 not valid"). I first checked for validity, found nothing , and then tried to narrow it down to the faulty line: 
First, I tried the part 1-50, then 51-80, then the rest and all that worked fine, so in fact, there was no misformed csv. Could it be, that the buffer size is too small? Then the cut-off would probably not be at a line break and that would lead to a not well formed csv.

**Comment by marius-wieschollek** [comment]
I will check this on the weekend

**Comment by marius-wieschollek** [comment]
I'm not sure if i could reproduce your exact bug. However i have tested the CSV import with a [database of 128 passwords](https://git.mdns.eu/nextcloud/passwords/wikis/_files/Sample%20Passwords.json). I fixed a few bugs on my part, but i also found some issues in the csv parser library which i'm using. Also it seems like Keepass and Passman do not always create valid CSV files. Because of this i will deactivate these importers until the tickets [PapaParse #459](https://github.com/mholt/PapaParse/issues/459) and [Passman #419](https://github.com/nextcloud/passman/issues/419) are resolved.
