### ISSUE TITLE
Problem with loading modules Marked and SimpleMde

### ISSUE THREAD

**Issue by magoralczyk** [marius-wieschollek/passwords#26]
I did install the nightly version (27 Feb) and now I am having new problems, I did not have before:
When I click on details, I get " the module Marked could not get loaded. Possibly the connection to Nextcloud is broken" and when I click on edit, I get " the module SimpleMde could not get loaded. Possibly the connection to Nextcloud is broken" and the NoticeBox is no longer present. I translated the error messages, so they are not verbatim. 

I reverted to another nightly (23 Feb) working fine. If you cannot reproduce those errors and need me to investigate more, I will install it and try again, but until you order me to do that, I will stay  with the working version.

**Comment by marius-wieschollek** [comment]
Those modules are loaded dynamically now in order to reduce the file size of the app. If they can't be loaded it means that the request failed.
Can you open the browser console (press F12) and check the value of `oc_appswebroots.passwords`. It should contain the actual path to the passwords app. If you are running your Nextcloud in a subfolder that should be included too. 

(with the current nightly) You could also check if the files `simplemde.js` and `marked.js` are in the folder `apps/passwords/js/Static`.

If that is the case, you might open the "Network" tab of your browser console and reload the page. Then open the details or the new password dialog. This should trigger a request. Check the url of the request and check if there is anything wrong with it.

**Comment by magoralczyk** [comment]
If I click on details, I get the error: Loading chunk 4 failed at HTMLScriptElement.u (common.js?v=ffe3bd9b-0:1)

The value of oc_appswebroots.passwords is "/nc/apps/passwords" (So the subfolder /nc/ is included).

Both js files are at the right place.

If I look into the network monitor, I see no problems, all calls get 200 back and I see that marked.js  and simplemde.js gets also loaded without problems (200, from disk cache). I tried to reload with cleared caches (ctrl+F5) but those two came again from disk cache...

That was in chrome, so I tried in firefox, and here works the details dialogue and only the edit dialogue gets the SimpleMde warning (again ctrl+F5).

So I tried both browsers in in incognito mode and that worked in both browsers without errors. So in the end it seems to be a caching problem (other version from the cache than needed?) but ctrl+F5 is not working in chrome nor in firefox.

**Comment by marius-wieschollek** [comment]
That looks like a caching problem. You can try to clear the browser cache for [firefox](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache) and [chrome](https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en) manually and try again.

**Comment by magoralczyk** [comment]
When deleting caches manually, it works in both browsers. Decide for yourself, if the issue can be closed.
