### ISSUE TITLE
NetworkError when attempting to fetch resource - App conflict

### ISSUE THREAD

**Issue by Excel1** [marius-wieschollek/passwords#267]
### System Information
- Nextcloud Version: 18.04
- PHP Version: PHP 7.3
- Database and Version: MariaDB 10.4
- Passwords Version: 2020.5.0
- Browser and Version: Firefox 76.0 / Chrome
- Client OS and Version: Windows 10
- Server OS and Version: Ubuntu LTS 18

### Steps to reproduce
1. Install Passwords App and configure it: Password works
2. Install and Configure OpenID Connect App: https://apps.nextcloud.com/apps/oidc_login - OpenID Connect Works
3. Login with local or OpenID Connect Account and go to saved passwords: NetworkError when attempting to fetch resource

### Expected result
I retrieve my passwords like everytime.

### Actual result
App loads but shows Notification: NetworkError when attempting to fetch resource
Browser JS Console: "TypeError: NetworkError when attempting to fetch resource."

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"gwCf7JyCecPdJ0ntdPrI","level":2,"time":"2020-05-04T11:37:45+00:00","remoteAddr":"162.158.89.139","user":"TestUser","app":"passwords","method":"GET","url":"/index.php/apps/passwords/api/1.0/service/favicon/192.168.178.20/32","message":"Attempt to access expired or nonexistent session a624e41c-eaf3-404a-9e96-cd5915a974e6 by TestUser","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0","version":"18.0.3.0","id":"5eb001eb86287"}
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
TypeError: NetworkError when attempting to fetch resource.
```
</details>

Could be the same problem: https://github.com/pulsejet/nextcloud-oidc-login/issues/8

**Comment by marius-wieschollek** [comment]
Thanks for letting me know about this issue. Also thank you for the research you already did on this issue.

The other issue from oidc seems to be related, but the PasswordlessTokenException discussed there is not really relevant because the passwords app continues just fine without it.

But while debugging i found that there seems to be a more general issue with the handling of app passwords / tokens and CORS. When Nextcloud finds the CORS annotation in a controller, it [logs you out and then logs you back in with the user and token provided in the request](https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Middleware/Security/CORSMiddleware.php#L91). This is … interesting. When a user is logged out, the oidc app just [redirects you to the logout page and kills the request](https://github.com/pulsejet/nextcloud-oidc-login/blob/master/lib/AppInfo/Application.php#L64).
That way you get a network error every time the passwords app tries to access the api.

I will see if i can do anything about this and if not, i will reach out to the developer of the OpenID Connect app to solve this issue.

If you're looking for a temporary fix for this, you can edit the [logout hook of oidc](https://github.com/pulsejet/nextcloud-oidc-login/blob/master/lib/AppInfo/Application.php#L63) from this
```
                $userSession->listen('\OC\User', 'postLogout', function () use ($logoutUrl) {
                    header('Location: ' . $logoutUrl);
                    exit();
                })
```
to this
```
                $userSession->listen('\OC\User', 'postLogout', function () use ($logoutUrl) {
                    if(strpos($_SERVER['REQUEST_URI'], 'passwords/api/1.0') !== false) return;
                    header('Location: ' . $logoutUrl);
                    exit();
                });
```
to just simply disable the hook for any request that goes to the api of the passwords app.

**Comment by Excel1** [comment]
@marius-wieschollek Thank you for the quick and detailed reply! I tested the workaround and it works pretty well.

**Comment by marius-wieschollek** [comment]
I assume you also specified the `oidc_login_logout_url` in your configuration?

**Comment by Excel1** [comment]
Yes:
`'oidc_login_logout_url' => 'https://cloud.example.com/auth/realms/connect/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Fcloud.example.com%2F'` (changed my domain with cloud.example.com)

**Comment by marius-wieschollek** [comment]
I have found no way around this in my app, so i commented the linked issue and hope that this can be fixed by the oidc app.
