### ISSUE TITLE
Plugin tries to load a file from raw.githubusercontent.com

### ISSUE THREAD

**Issue by ohreally** [marius-wieschollek/passwords#288]
Hi,

This plugin tries to load an external file from raw.githubusercontent.com. This makes me very uncomfortable, especially for an app that I entrust with all my passwords. Could you explain why this happens, and if/how I can disable this?

Thanks,
  Rob

**Comment by marius-wieschollek** [comment]
_This is not a bug report, and since you deleted the bug report form to ask your question i'm sure you knew this._

Please go to the [new issue page](https://github.com/marius-wieschollek/passwords/issues/new/choose) and choose one of the contact options intended for questions.

Since the privacy of the users is of paramount importance to this app, the admin manual contains a list of all third party domains which are contacted by the app and also ways to change this or host the remote service yourself.
