### ISSUE TITLE
Password Import from CSV throws invalid file type {type} when selecting file

### ISSUE THREAD

**Issue by Kai-Angne** [marius-wieschollek/passwords#29]
Thanks a lot for your work Marius - very usefull app!

### System Information
- Nextcloud Version: 13.0.0
- PHP Version: 7.2
- Passwords Version:  2018.4.0-build2046 (and stable versions before)
- Browser and Version: Google Chrome and Firefox - both newest
- Server OS and Version: Nginx / Ubuntu 16.04

### Steps to reproduce
exporting from Keepass to CSV (just one password or a bunch of passwords)
try to import whatever preselected structur - generic, Keepass (thx for putting in Keepass!) 

### Actual result
direct after opening the file i get this javascript error: wrong file type {type} produced by app.js
Same CSV worked with Passman App.
I tried a lot of different things but always the same result.

I don't have ideas anymore - except putting in hundred passwords manualy ;-)

Thx a lot
Kai

**Comment by marius-wieschollek** [comment]
Hi and thank you for the report. Could you tell me which OS you are using on your computer?

Also i released a new nightly build ([2018.4.0-build2050](https://apps.nextcloud.com/apps/passwords/releases)) to the app store. It does not fix the issue, but when you press F12 to open the browser console and then open the file, it should print the file details. It would be great if you could look for the `type` field and tell me what it contains. If there is no type field, please tell me which fields there are.

Also i assume that you have already tried the nightly because you noticed the KeePass import. I should mention that the reason why it currently isn't in the stable version is that there is an [upstream issue with the csv parser](https://github.com/mholt/PapaParse/pull/460) which may prevent Keepass files from loading if quote characters are being used within a field. The workaround for this is to open the file with an editor (like Notepad++ etc.) and to replace the occurrences of `\"` with `""`.

**Comment by Kai-Angne** [comment]
Hi Marius,

the computer im testing on is running Windows 10. I will do a test on a Linux machine later.
I had the same effect with the stable version of Passwords.
The Keepass CSV is clean standard - comma separated and text qouted with ". No Backslashes. I did a simple testfile with just three entries. Every import template throws the same error. 
Im pretty sure that the CSV file isn't really loaded (just touched). No errors or warnings in console while or after opening the file. So no printout of variables/fields.  

Short and dirty research looks like it might have to do with mimetype. I will check it on Linux. 
By the way - i'm pretty sure that when i test Passwords some weeks ago, the generic format filter works without that error message. But i didn't finished the import. 

Thanks a lot

**Comment by Kai-Angne** [comment]
Short - after switching to the newest nightly (build2050) the message changes: "Falscher Dateityp "application/vnd.ms-excel"" (wrong filetype). Looks like it is OS related - will come back with Linux result later.

**Comment by Kai-Angne** [comment]
Moin Marius,
works perfect with Linux - so it's related to the filetype/mime type. Under Windows I often deal with CSV and they are assigned to LibreOffice. I think you should extend your filetype check for Windows. 
Kai

**Comment by marius-wieschollek** [comment]
Don't close the issue so fast. I knew why i was asking for the os. On Windows there is usually no mime type given at all. But i assume that if you assign the files to a specific program, then it will be even worse and give you a wrong mime type (because the mime type of csv should be ` text/csv `). I think i will remove the mime type check alltogether and leave it to the users to select the right file.

**Comment by marius-wieschollek** [comment]
The [new build 2056](https://apps.nextcloud.com/apps/passwords/releases) should solve this. Instead of giving an error, it will just display a hint if the mime type seems to be wrong.
