### ISSUE TITLE
False server compatibility presistent warning

### ISSUE THREAD

**Issue by yward** [marius-wieschollek/passwords#314]
### System Information
- Nextcloud Version: 19.0.4 (Latest Stable)
- PHP Version: 7.4.7
- Database and Version: MariaDB 10.3.22
- Passwords Version: 2020.11.0
- Browser and Version: Firefox 82.0.3
- Client OS and Version: Windows 10
- Server OS and Version: Ubuntu 18.04.5

### Steps to reproduce
1. Login to nextcloud
2. A push notification by Passwords app appears containing the following:`
The upcoming version 2021.1.0 of Passwords will require at least Nextcloud 20 and PHP 7.4.0. To keep receiving security and feature updates, please update your server.`
3. Dismissing the message is not a solution as it'll reappear

### Expected result
What should happen?
The message should not appear as the server meets minimum requirements (Save for nextcloud 20 as it's still not in stable branch). At least dimissing the message should be permanent.
### Actual result
What does happen?
The server requirements message still appears. If you dismiss the message it reappears
### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
Irrelevant, just updater info
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
```
</details>

**Comment by marius-wieschollek** [comment]
The message is correct as 2021.1 will raise the Nextcloud requirements to NC 20.
Nextcloud 20 is listed as the latest stable version on the Nextcloud download page, and that's what i'm using as source. Since the stable channel does staged/incremental rollouts of "usually" the first bugfix version it may take months until it reaches everyone in that channel. That makes it useless to determine whether a version is the latest stable version.
The message only appears to admins which have admin notifications enabled and gets schedules after an upgrade of the app. That is the intended behavior.

For more info on the notification see the [manual page](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Notifications/Platform-Support-Notification).
