### ISSUE TITLE
2021.1.0 makes settings page crash

### ISSUE THREAD

**Issue by Omaha2002** [marius-wieschollek/passwords#331]
### System Information
**Server:**
```
 Put the output of "./occ passwords:system:report" here or fill out the fields below

 Nextcloud Version:  20.0.5
 PHP Version: 7.4.14
 Database and Version: MariaDB 10.4.17 
 Server OS and Version: ubuntu 18.04
 Passwords Version: 2021.1.0
```

**Client:**
```
 Browser and Version: Brave latest
 Client OS and Version: Windows 10 latest
```

### Steps to reproduce
1.  install or update to passwords 2021.1.0
2. go to settings page
3. internal server error
4. remove or disable passwords
5. go to settings page
6. settingspage shows

### Expected result
show settings page

### Actual result
internal server error on settings page

**Comment by marius-wieschollek** [comment]
is there any log entry related to this in the Nextcloud log.

**Comment by Omaha2002** [comment]
hmmm could this be similar to:  https://github.com/marius-wieschollek/passwords/issues/286

**Comment by Omaha2002** [comment]
I get a:


Exception: Unable to verify user xxxx@xxx.nl

/var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php - line 359:OCA\Passwords\Services\EnvironmentService->loadUserInformation("xxxxx@xxx.nl", OC\AppFramework\Http\Request {})
--

**Comment by marius-wieschollek** [comment]
Are you using a hardware device for login?

**Comment by Omaha2002** [comment]
Yup same as #286 loging in with local users works, loging in through AzureAD sociallogin breaks settingspage.

**Comment by Omaha2002** [comment]
Fixed with updating to 2021.1.1

**Comment by Omaha2002** [comment]
Fixed with updating to 2021.1.1

**Comment by Omaha2002** [comment]
and with 2021.1.2 the settingspage gives an internal server error again

**Comment by marius-wieschollek** [comment]
The 2021.1.0 from Friday and 2021.1.1 are the same version. I just raised the version number so that users from the 2021.1.0 from early january get the update. 2021.1.2 only removes a check during the upgrade. (ticket 330)

I guess that the issue is somewhere between the sociallogin app and [this function](https://github.com/marius-wieschollek/passwords/blob/master/src/lib/Services/EnvironmentService.php#L493). Usually there should be an empty password, but my guess is that there is no password at all or it's marked as a token login with no password.

I haven't been able to reproduce this so far. Maybe someone who experiences this can take a look at the contents of `$loginCredentials` when it happens.

**Comment by Omaha2002** [comment]
thank you for the clarification, the interesting thing i found out today is that if I login through AzureAD Sociallogin and right after I login go to the settingspage it works and if I come back to my laptop after some time it throws an error. I'm using Brave browser and I just turn of shield for my Nextcloud site so I'll check if it has something to do with that. For now I'll close the issue bc it seems not password app related.
