### ISSUE TITLE
KeePass Database Import

### ISSUE THREAD

**Issue by stondino00** [marius-wieschollek/passwords#347]
We like there is a mobile app for ios now available but we find keeweb more user friendly as it directly imports keepass database files and keeps the folder structure.

Please look at importing keepass database files and keeping the folder structure.

We are having 0 luck importing a keepass exported csv into passwords on nextcloud.

**Comment by stondino00** [comment]
Implementing keeweb into the passwords app so it can be used from the mobile app for nextcloud passwords, would be helpful and fix this issue.  Keeweb works 100% well with keepass database files.

https://github.com/keeweb/keeweb

**Comment by marius-wieschollek** [comment]
I have checked the keepass csv import. Apparently whatever keepass app i used to create the import back then did not have a group field which KeePassXC (2.6.3) and KeePassX (2.0.3) both have. I have added the field to the mapping. Aside from that i did not notice any issues, also not with notes.

Integrating keeweb into the passwords app is not something that is possible. (Details: https://help.nextcloud.com/t/integration-with-keepass/107597/2?u=mdw). Passwords uses a central database and provides an api so clients can access it. Keepass uses files that need to be available to the client. There is no interoperability between these fundamentally different basic concepts.
And creating an import for kdbx files seems to be difficult too, because their library kdbxweb apparently doesn't ship with everything that is necessary to decrypt kdbx4 files.

**Comment by monperrus** [comment]
FYI, with support for Keepass 2 XML, the folder structure would be preserved, see https://github.com/marius-wieschollek/passwords/issues/467

**Comment by monperrus** [comment]
FYI, wrote a Python script to translate a Keepass/Keepass2/KeepassXC database to the Nextcloud Passwords JSON backup format: https://gist.github.com/monperrus/5f3ca5ac9aa59159b33770701c0d5dc7

It preserves the folder structure as well as multiline "notes" fields.

**Comment by marius-wieschollek** [comment]
Closed in favor of https://github.com/marius-wieschollek/passwords/issues/467
