### ISSUE TITLE
Can't install passwords 2020.1.0 ... 

### ISSUE THREAD

**Issue by ArlasJ** [marius-wieschollek/passwords#348]
### System Information
**Server:**https://cloud.jagieniak.net
```json
 Run "php ./occ passwords:system:report debug" in your Nextcloud install directory and put the output here
 or fill out the fields below

 Nextcloud Version:
 PHP Version: 7.4.15
 Database and Version: MariaDB 10.5.8
 Server OS and Version: Debian 10
 Passwords Version: 2020.1.0
```

**Client:**
```
 Browser and Version: Firefox 85.0.2
 Client OS and Version: ArchLinux (newest)
```

### Expected result
What should happen?
Passwords should install from the appstore or occ:install passwords

### Actual result
What does happen?
It doesn't install. It shows following error only:  
```
The upgrade from 2019.7.1 is not supported. Please upgrade to 2020.1.0 first. See https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Migrations/Unsupported-Upgrade-Error for help 
```

I had removed passwords a while ago. I deleted the tables in the database (they weren't removed don't know why.) Did search for passwords in /var/www/nextcloud and found nothing what should link to version 2019.7.1.

**Comment by ArlasJ** [comment]
Solved it by myself. had to delete the passwords entries the appinfo table. But it is still a bug. Maybe you want to solve it?

**Comment by marius-wieschollek** [comment]
You should update to 2021.2.0.

The app doesn't delete user data when it's uninstalled since reinstalling the app is a common troubleshooting method. Admins would be unpleasantly surprised if their data was wiped while doing so. Deleting the passwords* tables from the database also does not delete all data.
For this reason uninstalling the app and reinstalling it later is still an update. And in that case the message is correct. 2019.7.1 is missing some migrations that are also no longer present in 2020.1.0. So this is not supported.

I have added info to delete all data and start over to the linked guide.
Aside from that i don't see anything that can be improved here.
