### ISSUE TITLE
is the passlink secure?

### ISSUE THREAD

**Issue by MichaelSp** [marius-wieschollek/passwords#383]
I just found out that passlink sends data to https://passlink.mdns.eu 
Probably not what "zero-trust" means. 

<img width="523" alt="image" src="https://user-images.githubusercontent.com/448282/117067590-81a15e00-ad2a-11eb-91de-80c7868cf1e8.png">

Just wondering if I'm still the only one having access to my passwords 🤔

**Comment by marius-wieschollek** [comment]
_Thanks for ignoring the issue template. That really gives me zero trust that you read anything i write. I would normally close this issue without comment since you apparently don't care enough about it to fill out the form. But in order to stop this discussion from getting out of control, everyone can read the answer right here:_

There is no contact to the passlink url when you have the extension installed. 
You don't need to believe me, you can read that right here in the code: https://github.com/marius-wieschollek/passwords-webextension/blob/master/src/js/Manager/PassLinkManager.js
This is simply a workaround for a missing webextension api in Chrome. If you care about your privacy, switch to Firefox where this can be handled properly with a custom protocol. Google just doesn't care enough about your data to offer that option in Chrome based browsers. (Additionally, Chrome and most Chromium-browsers are not open-source and can obviously see all your private data in the extension and NC app and do whatever it wants with that. But you trust Google not to do anything funny, do you?)

Even if you don't have the extension installed, the passlink server doesn't store anything, not even logs. It just serves a static page to whoever visits it telling them to install the extension. It's only purpose is to make sure that this domain isn't used otherwise. (But you can't verify that, i'm not aware of any way to prove that a server runs a specific software with a specific configuration)

If you look at the [setup guide](https://github.com/marius-wieschollek/passwords-webextension/wiki/setup-firefox-desktop) and the [code handling the setup on your server](https://github.com/marius-wieschollek/passwords/blob/master/src/lib/Controller/Link/ConnectController.php), you will see that the best you can do with the data in this url is to trigger the next step in the authentication process. This step requires the browser extension (or any other client) to send a code that is shown on the server and the extension (or whatever other client). Since all links are single use and the code is generated by the client, the passlink server would have a hard time if it tries anything funny.

If you want zero trust, check the handbook in the app (which fetches its data from Github) and set up E2E and read the code of the [app](https://github.com/marius-wieschollek/passwords), [browser extension](https://github.com/marius-wieschollek/passwords-webextension) and [js-client](https://github.com/marius-wieschollek/passwords-client/) to know what runs on your hardware.

**Comment by MichaelSp** [comment]
Thank you very much for taking the time to take my request/concerns seriously! 

I had a look into the links you provided. To be honest: I didn't know about the lack of custom protocol support in Chrome. 

Actually, there would be a way to "prove" that the server doesn't do anything funny. Well not really prove, but less likely: You could host the static html as github page. That way everybody could check the content and validate that there are no active parts on the server side (beside what github/microsoft operates). You could also connect your custom domain to github if you control the DNS. 

It's really hard to write secure code. But it's also hard to operate a server securely. In open source the source is under scrutiny but you never know what runs on the server.
I never meant to assume that you tamper with the data. 

BTW: I ignored the issue template since most (if not all) of the fields are not really relevant for the topic at hand. And I'm using Firefox as well as Chrome.

**Comment by marius-wieschollek** [comment]
> BTW: I ignored the issue template since most (if not all) of the fields are not really relevant for the topic at hand.

Don't do that! If this was a bug, my next step would have been to ask you exactly the things that are in the bug report from.
And since this isn't a bug, a question/discussion about this shouldn't be here anyway. That's why there are clear instructions on the new issue page. Ignoring that is just rude.

> Actually, there would be a way to "prove" that the server doesn't do anything funny. Well not really prove, but less likely: You could host the static html as github page. That way everybody could check the content and validate that there are no active parts on the server side (beside what github/microsoft operates). You could also connect your custom domain to github if you control the DNS.

Well, that wouldn't really solve the issue, but introduce also new downsides. Microsoft/Github definitely logs the request details. Neither i, nor users would have any influence over how that data is processed and shared. I would also have no control about what is behind that url, as Github is free to change the details of their hosting anytime. In that case it could happen that someone else is able to take over the page and there would no way to stop existing installations of the app from redirecting there.
Additionally, you might trust Microsoft/Github, but a lot of other users don't. Additionally, those are American companies so not only are the user privacy regulations less strict than in the EU, the US government also has the right to access that data and probably a lot more.

**Comment by MichaelSp** [comment]
Thank you again for taking the time to answer. Maintaining an open source project comes with a lot of challenges. And from experience I can say that dealing with questions like these is not the most fun part. So: Thank you!

Ok, so it comes down to: Do I trust you or do I trust Microsoft (with all the GOVs in the background)?

Fair question, I'd say. And the answer depends on many things. So, it's not that easy. Do you assume bad intentions manly coming from a state/gov or from malicious individuals/hacker-groups? But in general I try to avoid to trust in entities that I cannot control. For me, your infrastructure and MS infrastructure is the same. I can read the code, so I can control what runs on my system. But I cant check what runs on yours/MS's infra.

My personal preference: Larger corps have more to lose if they fail to deliver on the privacy topic. That's why I'd prefer GH-pages over your hosting.

Another option to avoid the question of "who is hosting", would be to offer a way to connect the browser plugin with the backend via cut+paste a login link, or maybe - just for the very paranoid like me - offer an option to enter everything manually. I saw in other places that you didn't like the manual way because some people might not understand it. Fair enough. But I would actually prefer a manual, less "magic" solution.

**Comment by marius-wieschollek** [comment]
> Larger corps have more to lose if they fail to deliver on the privacy topic. That's why I'd prefer GH-pages over your hosting.

Microsoft - [The first company to participate in the NSA Prism program](https://en.wikipedia.org/wiki/Criticism_of_Microsoft#Privacy_issues), [the company who helped China with censoring the internet](https://en.wikipedia.org/wiki/Criticism_of_Microsoft#Censorship_in_China), [wanted to require an always on kinect camera to use the xbox](https://www.ign.com/articles/2013/05/21/xbox-one-will-not-function-without-kinect-attached), put ads in the start menu and [continues to violate the GDPR with the Windows 10 telemetry](https://autoriteitpersoonsgegevens.nl/en/news/dutch-dpa-microsoft-breaches-data-protection-law-windows-10) - has failed "to deliver on the privacy topic" for decades now and not lost anything they seem to care about enough to stop. 

That's why i will keep my hosting rather than just hoping they won't do anything wrong with my data. Additionally, the server that hosts the passlink domain also hosts the code and does the completely automated deployments for the app and the extension. GitHub is just a mirror. So moving the passlink domain is a placebo because that server ships updates that your browser will install.

> Another option to avoid the question of "who is hosting", would be to offer a way to connect the browser plugin with the backend via cut+paste a login link, or maybe - just for the very paranoid like me - offer an option to enter everything manually. I saw in other places that you didn't like the manual way because some people might not understand it. Fair enough. But I would actually prefer a manual, less "magic" solution.

If you read the text in the first run wizard of the extension or the [manual setup guide](https://github.com/marius-wieschollek/passwords-webextension/wiki/setup-manual), you will see that this is already included. I'm actually really happy that no one reads that since users who can't copy a url were a major source of support overhead prior to passlink.
