### ISSUE TITLE
The plugin deactivates itself after round about 1 minute

### ISSUE THREAD

**Issue by siaccarino** [marius-wieschollek/passwords#43]
The plugin deactivates itself after round about 1 minute. There are no logs for this plugin visible.

### System Information
- Nextcloud Version:  13.0.0.2
- PHP Version: 7.1.14
- Passwords Version: 2018.4.2
- Browser and Version: Firefox 59.0.3
- Client OS and Version: Windows 10
- Server OS and Version: Linux x64

### Steps to reproduce
1. Activate plugin, wait 1 minute
2. error logs
- Undefined index: SCRIPT_FILENAME at /var/www/.../html/nextcloud/lib/base.php#144
- session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) at /var/www/.../html/nextcloud/lib/private/Session/Internal.php#175
- Directive 'safe_mode_protected_env_vars' is no longer available in PHP 5.4 or newer at Unknown#0
- Undefined index: {DAV:}getlastmodified at /var/www/.../html/nextcloud/lib/private/Files/Storage/DAV.php#582

### Actual result
Plugin is deactivated

### Expected result
Plugin shall remain activated

**Comment by marius-wieschollek** [comment]
The extension is deactivated because errors occur and Nextcloud tries to avoid those by disabling any third party extension related to these errors. The error log provided by you does not contain any error which i can link to the extension:

- `Undefined index: SCRIPT_FILENAME at /var/www/.../html/nextcloud/lib/base.php#144` is caused most probably because your webserver (apache, nginx or lighthttpd) does not provide the required environment variable (`SCRIPT_FILENAME`) to php and Nextcloud can not find it. This can lead to issues.
- `session_write_close(): Failed to write session data (files) [...]` is caused because there is an issue with the session data storage path (`session.save_path`) check if the path `/var/lib/php/sessions` exists on your server and if the PHP process (or webserver if you use modphp) can write to it.
- `Directive 'safe_mode_protected_env_vars' [...]` is only a notice caused by th use of the setting `safe_mode_protected_env_vars` somewhere in your php configuration
- `Undefined index: {DAV:}getlastmodified` is something i do not know exactly. A quick look in the Nextcloud Codebasis lets me assume that this caused when Nextcloud tries to connect to a remote WebDav service (Another Nextcloud, WebDav storage etc.) but the server sends incomplete response data

As i said before, i can not connect these issues to the extension itself. They seem to be general issues with your Nextcloud server. You might want to look at the [Nextcloud documentation](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/index.html) to fix them.

To figure out why Passwords won't work on your server, please check your error log again for entries with the App "passwords" or PHP errors with the path of the app in the error message.
![grafik](https://user-images.githubusercontent.com/8255857/39696328-b45f2f2a-51ed-11e8-9075-d929d14bb3df.png)

**Comment by siaccarino** [comment]
OK: Thank you - I forwarded it to my hoster...
