### ISSUE TITLE
Support Notes

### ISSUE THREAD

**Issue by chaptergy** [marius-wieschollek/passwords#442]
**Current Status**
The password field is required and has to be filled in order for an entry to be valid. This leads to no data being able to be saved which is not directly associated with a password. E.g. saving a small secret note, a link, a phone number (if you wouldn't want to have them unencrypted) or just saving the answers to multiple security question is not possible, or only possible by setting a dummy password. But this could be confusing and these entries are then usually marked as unsafe.

**Feature Description**
The password field is optional and you can save an entry without entering a password.

**Additional context**
I know the focus is definitely on passwords, but allowing to store small notes without a password would be useful in some cases.

**Comment by ghost** [comment]
Yes, Please!

**Comment by marius-wieschollek** [comment]
In case of Notes i can see the use case for this.

For security questions and maybe some of the others you might want to check if adding a custom field to the password they belong to fits your needs.

**Comment by sfatula** [comment]
In Enpass, I store passwords of course, but also notes, credit card info, identities, licenses, Memberships, Reward programs, and a few more. It functions almost as a free form information organizer. You almost have the features to replace that. By removing Password requirement and with your additional custom fields, pretty much you could support the same functionality and allow more people to use this addon. Your folders or tags could be the type of information, so that's already there. 

Another vote for this request.

**Comment by marius-wieschollek** [comment]
I would replace this with #71. Then you could just create your own "Notes" template
