### ISSUE TITLE
Pin/App Password support for browser access.

### ISSUE THREAD

**Issue by Saunders1991** [marius-wieschollek/passwords#455]
**Current Status**
If a browser is set up to automatically log into Nextcloud this app could easily allow someone to gain access to every password that is saved. (This is not a problem with the mobile app as it's possible to require a PIN/Fingerprint authorization before fully launching the app)

**Feature Description**
It would be really nice if you could add the option require inputting a pin-code or even your Nextcloud account password before being able to copy/view passwords.

**Additional context**
N/A

**Comment by lightlike** [comment]
That happens when you enable E2E encryption.
Every time you restart your Password App, it will ask for your password to decrypt the data.

See Client-Side Encryption here: https://git.mdns.eu/nextcloud/passwords/-/wikis/Users/Encryption

Found is Settings over here:
![grafik](https://user-images.githubusercontent.com/12970722/142818496-6727985f-ffb7-4c77-a6b4-3a4037dae0aa.png)

Please use a secure password for this and not just a PIN.

**Comment by Saunders1991** [comment]
Ahh ok, thank you for the quick reply. Works great!
