### ISSUE TITLE
Only LSR is offered from store for valid installation

### ISSUE THREAD

**Issue by sevmonster** [marius-wieschollek/passwords#470]
Despite meeting all prerequisites (Alpine Linux edge, NC23, PSQL, HTTPS, PHP 8, Zip, Imagick, Intl) I am shunted to LSR. Why is this?

### System Information
**Server:**
```
{
    "version": {
        "server": "23.0.0.10",
        "app": "2022.1.10",
        "lsr": true,
        "php": "8.0.14"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "pgsql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "random",
        "previewApi": false,
        "faviconApi": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": [],
        "cse": []
    }
}
```

**Client:**
```
 Browser and Version: Any
 Client OS and Version: Any
```

### Steps to reproduce
1. Go to the store and search for the Passwords app

### Expected result
Install normal Passwords app

### Actual result
Only LSR is available

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
N/A
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
N/A
```
</details>

**Comment by marius-wieschollek** [comment]
As far as i can see, the update to 2022.1.20 is distributed to compatible systems by the appstore. So i assume if that is not the case for you, the reason must be something not directly related to the app. I can think of several reasons:

- You recently upgraded PHP and Nextcloud has not yet updated the appstore data. In this case the update should appear after 1 - 2 days.
- Your server fetched the app list at a time when the LSR version was published but the standard version wasn't. This can happen because the NC appstore api crashes some times and as a result there may be a few minutes between the release of both versions. In this case the update should appear after 1 - 2 days.
- Your server uses PHP 7.4 or lower to execute cron jobs. In this case the system requirements are not fulfilled even if your web server uses PHP 8. In this case the passwords app settings likely have a warning informing you about the issue.

**Comment by sevmonster** [comment]
I believe it was 2. 2022.1.20 non-LSR appeared today after forcefully clearing the app store cache and redownloading the index. Thank you.
