### ISSUE TITLE
Import Passwords into a previously already created folder is not working

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [marius-wieschollek/passwords#491]
Sadly my last feature request was closed even though it was missunderstood.
I would therefore explain the problem again in more detail to avoid misunderstandings.

My goal is not to import folders and passwords, but to import passwords from a CSV into a folder that I had previously created myself in the Folders section in Nextcloud Passwords.

Currently I can only import passwords or folders.
But importing passwords and specifying a destination folder for the passwords during import is not possible.

Translated with www.DeepL.com/Translator (free version)

**Comment by marius-wieschollek** [comment]
> Sadly my last feature request was closed even though it was missunderstood.

Your last feature request was closed because you ignored the feature request form, just like in this one. That form is there to tell you how to describe your feature request in a way that prevents misunderstandings and provide the necessary detail. As written in the feature request form `Incomplete tickets and tickets not describing a (single) feature will be closed`

>  But importing passwords and specifying a destination folder for the passwords during import is not possible.

Yes it is. If you import a CSV with a folder assigned to the passwords, the passwords will be placed in that folder. Check the "Import from custom CSV" article in the handbook in the app for more infos.

**Comment by GVLLIFESTYLE** [comment]
OK, I understand.
You can really close the request now ;)
