### ISSUE TITLE
Be able to not show upgrade warning

### ISSUE THREAD

**Issue by pierreozoux** [marius-wieschollek/passwords#504]
Hi,

we are running Nextcloud 22 (which is a supported version), and password version 2021.12.20
We try to offer our users a SaaS experience, where they don't have to worry about updates or php.
(Most users probably don't even know what php is :) )

Currently we have this warning:

![Capture_d_écran_2022-05-20_à_10 44 34](https://user-images.githubusercontent.com/1863453/169506173-f34e74e2-2e48-4bf4-a21d-a3162fb10002.png)

Is it only for the admin of the instance?
Is it possible to configure it to not show it at all?

I understand the feature for hackers like us that like to tinker, and know about the lastest and greatest :)
But I can already see the face of my users starting to panic with this warning :P 

Thanks a lot for this app :)

Cheers!

**Comment by marius-wieschollek** [comment]
This message is triggered by [this file](https://git.mdns.eu/nextcloud/passwords/-/wikis/Users/_features/features-v1.json).
Since you're hosting NC for others, I would recommend [this guide](https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/User-Handbook/Self-Hosting) to supply the handbook yourself. That way you can also use feature switches to enable or disable features and control which apps are shown in the apps section.

**Comment by marius-wieschollek** [comment]
Additionally, newer version of the app don't have that message anymore. They only notify admins once the last planned update for their version of NC is installed.

**Comment by pierreozoux** [comment]
Ok, Thanks for the hints!

To be honest, I don't really understand this thing about the handbook that can modify the features of the app itself.

But anyway, if in the next version, there is no longer this warning, then, it is all I need :)

Thanks again :) Have a nice weekend!
