### ISSUE TITLE
Password not working when internet not reachable

### ISSUE THREAD

**Issue by GilZm** [marius-wieschollek/passwords#510]
hello

I'm hosting Nextcloud at home and I'm currently experiencing an issue with my internet access provider. 

Despite I'm able to use my nextcloud server, the password app is not working, which is kind of annoying because my internet access provider password is in ... password app !!

I've been able to detect and temporarily patch the main issue (call to https://raw.githubusercontent.com/wiki/marius-wieschollek/passwords/Users/_features/features-v1.json nextcloud.log message: "/var/www/html/custom_apps/passwords/lib/Services/DeferredActivationService.php","line":146,"function":"getFeaturesFromRemote"... exception message : ""cURL error 6: Could not resolve host: raw.githubusercontent.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)") - at least, now I've access to my password !!

I found another dependency within HaveIBeenPwnedHelper.php which now prevent password entries creation or update.
(nextcloud.log message : "/var/www/html/custom_apps/passwords/lib/Helper/SecurityCheck/HaveIBeenPwnedHelper.php","line":48,"function":"isHashInHibpDb"... exception message : "dns_get_record(): A temporary server error occurred. at /var/www/html/lib/private/Http/Client/DnsPinMiddleware.php#83")

would you mind adding exception handling so that such issue would not prevent using password app ?

Gilles

**Comment by marius-wieschollek** [comment]
This issue does not follow any issue template and will therefore be closed.
If you're requesting a feature, please use the feature option on the new issue page, if this is a bug, please use the bug template.
Otherwise i suggest you check the manual on for offline use: https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/F.A.Q#how-do-i-use-the-app-on-a-server-without-internet-access
