### ISSUE TITLE
Central approcah for data collection

### ISSUE THREAD

**Issue by christianlupus** [marius-wieschollek/passwords#541]
**Current Status**
Currently, the password app collects user statistics in anonymized form.

**Feature Description**
I think a more cooperative approach between the app developers might reduce work and generate a more flexible solution for all. 

**Additional context**
I opened the [discussion on the forum](https://help.nextcloud.com/t/generic-domain-for-app-development/147153) related to a common app domain. It soon went down the road if the collection of user data is an option or not. I am now opening a few issues to make app developers aware of the discussion and eventually collect some (good :wink:) arguments.

**Comment by marius-wieschollek** [comment]
1. I don't want telementry in my app. But Nextcloud doesn't share their data so what else can i do?

2. I would be in favor of Nextcloud / Nextcloud Appstore collecting or providing the already collected data to me instead of me doing that myself. This would be similar to e.g. Mozilla Addons where i get to see selected statistics of how my addon performs and who is using it without me having to care about the privacy and data handling. If i can hook into that and add some extra info: great!
Nextcloud already collects that data, so i don't really see the need for in app telemetry.

3. I would not use any third party service or even just a third party domain (i.e. not me or the Nextcloud Project) for anything related to the app. That just violates the promise i made to the user about how their data is collected. 

4. I would also not use third party domains because similar services (e.g. Ethereum Name Service) have had issues with that before.

5. I do have several things where a central domain would have been useful, such as [this demo](https://test.passwordsapp.org/info.html), [this blackhole domain](https://link.passwordsapp.org/), [this](https://breached.passwordsapp.org/) and [this](https://icons.passwordsapp.org/) and obviously [statistics](https://statistics.passwordsapp.org).

6. As a user/admin i would rather have one central configuration for usage statistics instead of having to check if and how apps collect data. My app only collects data if you opted in and you're actually using the app, i don't know how others do it.

7. I collect that data to make decisions over which things i should look into or how changes i made affect users. Here a few examples:
    - PHP support: Providing a special version for users with PHP 7.4 (the app only supports 8.0) was a lot of effort for something i don't use, but ~40% of users switched to that version instead of keeping an outdated version installed.
    - NC support: I can also see that when i drop support for older in january, people stay on the older version longer. For me that means that the december version of my app needs to be as bug free as possible, but the january version can add new features that may still have some unknown issues. I can also see that few people use really old NC versions and these also don't update the app itself. No use in supporting something that noone uses.
    - Nextcloud updates: I learned that most people don't update NC until the first or second bugfix release. That means i should have an update ready, but it doesn't have to be perfect as most users will upgrade later.
    - Features: I can see what is used and what isn't. My app offers three password security checks. Should i add more? No, 97,5 leave the default. 
    - Client Compatibility: When removed the legacy api, i could do so knowing that it was really not used anymore.
    - Migrations: I can see if migrations work without waiting for user feedback. The implicit server side encryption migration didn't work as fast as i thought, i changed that and now it does. No user would have ever noticed that.
    - App integrations: I can check if other apps are commonly installed with mine. Why offer a Passman migration if only 3% used it?
    - Beta versions: Not many use them, because Nextcloud provides no UI for doing so. I know because i tracked that. I added a button that does that and now there are more than twice as many beta testers.

As you see, most of the things i listed above are focused on me having less work to do. That's a good thing because three major Nextcloud updates per year already cause a lot of work. I would rather spend the rest of the time developing features users actually want instead of catering to someone who wants a very niche feature but blows up my issue tracker and support channels.


Also my data is free to use as is, [here is the json](https://statistics.passwordsapp.org/data.json).

Since this is not really a feature request, i will close this ticket. Please use the support options for similar questions.
