### ISSUE TITLE
Passwords in the User Migration App

### ISSUE THREAD

**Issue by ghost** [marius-wieschollek/passwords#556]
**Current Status**
Passwords can only be exported and imported within the Password app.  Which makes it easy for users to lose track.

**Feature Description**
For exporting and importing passwords, it would make sense for users if all data that can be exported and imported are managed in one place.  For this it would be advisable to use the functionality of the User Migration App from Nextcloud.

**Additional context**
https://apps.nextcloud.com/apps/user_migration

![export.png](https://user-images.githubusercontent.com/90777102/210184999-67737f2e-c9ba-41cc-bcbf-c527894768f9.png)

**Comment by marius-wieschollek** [comment]
yet another export feature…

I added basic support for this, but it only works if you don't have end-to-end encryption.
Since this export is created on the server there is some data where the server side encryption can't be removed when e2e is enabled. This data can't be added to the export since the server where it's imported won't be able to decrypt the data.

For users with e2e enabled i added a notification that just tells them to use the already existing import in the app.

For users without e2e, this import will add their decrypted data to the export.

**Comment by marius-wieschollek** [comment]
Is part of the release 2023.1.0

**Comment by ghost** [comment]
When opening the user menu (user migration) the following error message appears: Could not estimate export size for Passwörter

**Comment by marius-wieschollek** [comment]
@R7JANV1 Do you see an `Query is selecting * and specific values in the same query. This is not supported in Oracle.` error when this happens?

**Comment by ghost** [comment]
Yes.
