### ISSUE TITLE
Username needs to be more accessible

### ISSUE THREAD

**Issue by HanPrower** [marius-wieschollek/passwords#6]
The migration tool made everything [username]@[website], but that's not very useful in the long term or for usability. I also wouldn't insert things like that as I want to be able to scroll down via the website name not my username.

Either the username needs to be generally visible or a "Copy username" needs to be in the menu and/or the sidebar needs to be able to pinned open.

If I need to get a password via a mobile device it'll be hard to access currently.

**Comment by marius-wieschollek** [comment]
The [user]@[website] is the default label generated whenever no label is defined by the user. Since the old app did not have labels, the migration tool uses this. You can edit the label for each password, but right now there a no other options for the default label.
If this is a major inconvenience for you, you can use the hidden backup tool (add #/backup to the url) to export your passwords and edit the json file and replace the labels there (regex from `"label"\s+ : "([^@]+)@([^"]+)",` to `"label" : "$2 - $1",` should be good). Then import the file and choose "Overwrite always". But since the backup tool is not well tested i strongly recommend a database backup before this.

The username can be copied by double clicking. I have made a menu entry available on mobile phones and may include a setting to show this on desktop in the future.

The mobile ui horrible at the moment. I have added some fixes improve the situation. If this is important to you, you can download the latest build on the [builds page](https://git.mdns.eu/nextcloud/passwords/pipelines). (Click on the download menu and select "Download Pack artifacts")

**Comment by HanPrower** [comment]
Ah, gotcha. I wasn't complaining about the migration tool, just pointing out that w/o a Copy Username function having to use that format would be tedious to me.

It's definitely a must to have another way to get at the username easily. Now that I know I can double click that's fine, but usability would generally dictate that won't work for everyone. People with bad fingers/hands or those with mobility control issues may never be able to achieve the speed or accuracy to do it. Copy Username always being present in the menu would be a trade off for reducing the visual clutter and keeping that usability.

I tried the backup tool, but import seemed to fail w/o any feedback anywhere. That's fine though I want website titles there anyway, so I'll be manually editing them when I get around to it.

**Comment by marius-wieschollek** [comment]
@HanFox I think you will like the newest nightly. It adds three ui settings:
- Use a different field like user or website as title
- Sort passwords by a field that is not the title field
- Show copy password and username in the menu

The settings can be found in version 2018.3 if you click on "more".
What do you think?

**Comment by HanPrower** [comment]
When setting it to display as the website name it gets a little bit weird with some domains:
![passwords-websitesort](https://user-images.githubusercontent.com/1781312/36932258-57ec2ca0-1ebe-11e8-9c63-23617387652c.png)

It's only doing that on some websites (seemingly, for me, only ones ending in .uk), but not all of them (e.g currys.co.uk is a non-jumbled .co.uk domain).

The other settings are very useful and appear to be working correctly :+1:

**Comment by marius-wieschollek** [comment]
Seems like it is in the wrong order. i will fix that with the next nightly

**Comment by marius-wieschollek** [comment]
Domains should be fine now
