### ISSUE TITLE
Search tab: just the tab's credentials or all credentials?

### ISSUE THREAD

**Issue by kbridger** [marius-wieschollek/passwords#68]
I'm wondering if this is a feature request or just not understanding the intended use of the hourglass search function.

In my experience the UI that pops up when clicking the browser extension provides exact matches for the site as well as an ability to search through all my credentials in case the site matching algo failed, or I just wanted to look up a credential without opening the associated page.

The behaviour I see though is that clicking the hourglass exposes a search, but it seems to only search for matches to the site shown under the popup.  So there's no way to search through all the credentials without opening the main Nextcloud website and choosing to view the Passwords app.

If the current behaviour is the intended then I'd like to file a feature request to support searching all credentials through the browser plugin, not just that specific site's.  It feels like the existing hourglass tab works well, just the scope of the search should be broadend.  If the current behaviour I'm seeing (search limited to credentials for current tab's domain only) isn't intended, is there a setting or something I can check to see why it is not working?

Thank you in advance for this great app - I was using Passman and felt it was perhaps experiencing attrition and having a solid password manager for NextCloud is so very awesome.  I prefer this UI as a much more polished experience too - great work!

**Comment by marius-wieschollek** [comment]
Hi and thanks for your request.
If i understood you correctly, you are referring to the search tab in the browser extension.

The search tab uses a temporary database to search for passwords.
This means that the browser extension will fetch all passwords from the app when the browser is opened and then use this temporary copy to search. 
This also means that the browser extension may have an outdated database when new passwords are added in the app. You can refresh the database manually by clicking the refresh icon in the top right corner.
The search tab in the browser extension is also quite limited because the extension still uses an older API. Because of that, the search tab will only search the username, hostname, notes and the password itself. If you try to search a password by its name or any other field it will not be found. 
There is already an [issue](https://github.com/marius-wieschollek/passwords-webextension/issues/8) open to improve the search but i do currently not have the capacity for it.

**Comment by kbridger** [comment]
Thanks for the reply Marius.  You've nailed it on the head.  The browser extension's search does indeed search across all credentials, I just wasn't using one of the searchable fields' values to search by.

I just tested by searching for a string in the hostname and it works, finding matches across all sites, not just the current tab's credentials.
