### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by mokkin** [marius-wieschollek/passwords#691]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [ ] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{"reqId":"a9y1uY7AdbGKz6IL27XN","level":2,"time":"2024-11-20T12:06:49+01:00","remoteAddr":"2a00:1f:5c01:xxxx:yyyy:zzzz:aaaa:f2f7","user":"some.user","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"Icon of notification is not an absolute URL and does not work in mobile and desktop clients [app: passwords, subject: share_create]","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0","version":"30.0.2.2","data":[],"id":"673dc2ebccdaa"}
```

### Client Information

Browser and Version: Firefox 131.0.3
Client OS and Version: Ubunt 22.04

### Bug description

The error message is thrown into the log every minute

### Steps to reproduce

checking the log ;)

### Expected behavior

no message or just once per hour

**Comment by marius-wieschollek** [comment]
Couldn't find this error when checking my log ;).
That's likely because the app uses absolute URLs for notifications for [over two years](https://github.com/marius-wieschollek/passwords/commit/77094cd12beaff68f637050c735a5b5bc7b6ea80).

I recommend updating to the latest version of the app and maybe clearing your notifications once in a while. This error message is likely caused by a notification that has been sent years ago.
