### ISSUE TITLE
Create less log entries

### ISSUE THREAD

**Issue by Somebodyisnobody** [marius-wieschollek/passwords#70]
Passwords floods my system logs with informations from cron. It's heavy scrolling because about 80% of the log is the every 15 minutes cron-job which threads passwords. If I want to search an information about "one updated share" I cannot search thousands of lines.

The best way in my opinion is a small statistic on the settings page of passwords.

Other options:
* Maybe a checkbox to set the logging-level to debug
* Or a checkbox to just log if something was updated/deleted/removed/created
* Or a mix of them: checkbox to set the logging level on "debug" for "Hey I was executed" and logging-level on "info" for "Hey i changed something: ... ... ..."

How do you feel about that?

**Comment by marius-wieschollek** [comment]
I think an option for this is overkill since most people never check their logs or have it set to warnings and exceptions only.

All the messages have a number in them (Like `Updated 123 share(s)`). This number could be used by the logger to assign the messages where nothing happened to the `debug` level and anything else to `info`. 

I would also like to suggest to use the search bar, but at least on my Nextcloud 14 this causes a PHP notice which causes more log entries :laughing:

**Comment by Somebodyisnobody** [comment]
Thank you 😄
