### ISSUE TITLE
https error

### ISSUE THREAD

**Issue by Aviortheking** [marius-wieschollek/passwords#75]
### System Information
- Nextcloud Version: 14.0.0
- PHP Version: 7.2
- Passwords Version:  2018.9.1
- Browser and Version: Firefox, 62.0.2 64-bit
- Client OS and Version: Windows 10 PRO, 17134.286
- Server OS and Version: idk, idk (OVH webserver)

### Steps to reproduce
1. Tell us how to reproduce your issue.
install password
activate https via the .htaccess
```
  RewriteCond %{HTTPS} off
  RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R,L]
```
2. Provide sample data if needed
3. Include relevant user settings and app settings if not standard

### Actual result
What does happen?
this shows up 
![capture](https://user-images.githubusercontent.com/15822031/45998860-69620080-c0a4-11e8-90db-47f30737d7b0.PNG)

### Expected result
What should happen?
i should have access to my passwords

**Comment by marius-wieschollek** [comment]
Can you enable HTTPS debugging and post the result of it?

**Comment by Aviortheking** [comment]
Well i cant change any settings for your app... Whem i check the debugging there is no save button nor there is autosave

**Comment by marius-wieschollek** [comment]
Actually there is autosave. Any setting that is changed will be saved automatically and a green "saved" message will appear at the top. Also if you check the box and reload the page afterwards, the https debugging info should appear as a small blue box in the bottom right corner right away.

**Comment by marius-wieschollek** [comment]
I just realized that the admin settings can't save if https is not detected. I will fix that in the next release. 

You can either run `occ config:app:set passwords debug/https --value=1` from the command line, or go to the "Overview" section in the admin settings and check if Nextcloud [reports HTTPS to be enabled](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/security_setup_warnings.html#you-are-accessing-this-site-via-http). 

Usually hosting services will run Nextcloud behind a proxy. In that case you need to set the `overwriteprotocol` option in the config.php so that Nextcloud actually knows that HTTPS is being used.
(See [reverse proxy documentation](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/reverse_proxy_configuration.html#overwrite-parameters))

**Comment by Aviortheking** [comment]
well overwriteprotocol is working so I'll close the issue thanks for the help
