### ISSUE TITLE
Share don't work

### ISSUE THREAD

**Issue by caohee** [marius-wieschollek/passwords#87]
I'm using nextcloud for less than a month and just loving it. I've read a lot about this problem but I have not been able to reach a conclusion. Does anyone know some simple way to make the share work in password app? Thank you very much for your attention.

**Comment by marius-wieschollek** [comment]
Hi. Please read the new issue template before opening the issue and follow the instructions.
You should check the [solved issues](https://github.com/marius-wieschollek/passwords/issues?utf8=%E2%9C%93&q=is%3Aissue+sharing) since others may have had the same issue.
If you have a problem setting up sharing, please go to the [Nextcloud Forum](https://help.nextcloud.com/c/apps/passwords).

**Comment by marius-wieschollek** [comment]
Closed because of no reply
