### ISSUE TITLE
Passman JSON import omits custom fields

### ISSUE THREAD

**Issue by budachst** [marius-wieschollek/passwords#91]
- Nextcloud Version: 14.0.3
- PHP Version: 7.2
- Passwords Version: 2018.10
- Browser and Version: Chrome 70.0.3538.67/FF 62.0.3
- Client OS and Version: macOS Mojave
- Server OS and Version: Debian 9.3

When importing a Passman JSON file, the import does not import, or skips, any custom field present in the JSON file. This is particularly problematic, as they tend to contain other passwords, e.g. app passwords or NC 2FA app keys.

### Steps to reproduce
1. have a passman credential with custom fields and export it as JSON
2. import JSON into passwords

### Actual result
Credentials loose all of their custom fields

### Expected result
custom fields should be migrated to passman's own extra fields

**Comment by marius-wieschollek** [comment]
Passwords can now import custom fields from Passman.
Due to differences in the architecture of the apps, there are some incompatibilities.
For example you can not import files attached to Passwords.

A full list of compatibility issues and help for the Passman Export can be found in the app under "More" > "Handbook" > "Import from Passman"
